<!doctype html><html lang="de"><head><meta charset="utf-8"><title>Zuordnung Domains zum Kunden</title><style>
*{box-sizing:border-box}body{margin:0;background:#d4d0c8;font:12px Tahoma,Arial;color:#111}.wrap{padding:18px}.top{display:flex;justify-content:space-between;align-items:center}.layout{display:grid;grid-template-columns:340px 1fr;gap:22px}.box{border:1px solid #888;padding:10px;background:#ddd}.list{background:white;border:1px solid #888;max-height:450px;overflow:auto}.item{display:grid;grid-template-columns:70px 1fr 150px;gap:6px;padding:4px 6px;border-bottom:1px solid #ddd;align-items:center}.domain{grid-template-columns:1fr 120px}.button{display:inline-block;padding:5px 10px;border:1px solid #777;background:#eee;color:#111;text-decoration:none;cursor:pointer}.search{display:flex;gap:5px;margin-bottom:8px}.search input{flex:1}.assign{display:grid;grid-template-columns:110px 1fr;gap:6px;align-items:center;margin-top:10px}.ok,.err{padding:6px;margin-bottom:8px;border:1px solid}.ok{background:#e8f6e8}.err{background:#fee}.hint{font-size:11px;color:#555}.selected{background:#eef}
</style></head><body>
<x-page-help title="Domain-Kundenzuordnung">Hier werden Domains einem Kunden zugeordnet bzw. bestehende Zuordnungen geprüft. Änderungen beeinflussen, welchem Kunden eine Domain fachlich gehört.</x-page-help>
<div class="wrap"><div class="top"><h2>Zuordnung der Domains zum Kunden</h2><a href="{{ route('frontend.switch','modern') }}">Zum neuen Frontend wechseln →</a></div>
@if(session('status'))<div class="ok">{{session('status')}}</div>@endif @if($errors->any())<div class="err">{{implode(' · ',$errors->all())}}</div>@endif
<div class="layout"><div><div class="box"><b>Nicht zugeordnete Domains</b><form class="search" method="get"><input name="domain" value="{{$domainSearch}}" placeholder="Domain suchen"><input type="hidden" name="kunde" value="{{$customerSearch}}"><button class="button">Suchen</button></form><div class="list" id="domains">@forelse($domains as $d)<label class="item domain"><span><input type="radio" name="pick_domain" value="{{$d->intID}}" data-name="{{trim($d->strDomainname)}}" data-date="{{date('Y-m-d',strtotime($d->datRegistriertAm))}}"> {{trim($d->strDomainname)}}</span><span>{{date('d.m.Y',strtotime($d->datRegistriertAm))}}</span></label>@empty<div style="padding:8px">Keine unzugeordnete Domain gefunden.</div>@endforelse</div><p><a class="button" href="{{route('domain-create.create')}}">Domain neu</a></p></div>
<form class="box" method="post" action="{{route('domain-customer.assign')}}">@csrf<div class="assign"><label>Domain</label><input id="domainName" readonly><label>KundenNr.</label><input id="customerIdDisplay" readonly><label>Registriert am</label><input id="registeredAt" type="date" name="registered_at" required></div><input type="hidden" id="domainId" name="domain_id"><input type="hidden" id="customerId" name="customer_id"><p><button class="button">Zuordnen</button></p></form></div>
<div class="box"><b>Vorhandene Kunden</b><form class="search" method="get"><input name="kunde" value="{{$customerSearch}}" placeholder="Kundennummer oder Name"><input type="hidden" name="domain" value="{{$domainSearch}}"><button class="button">Suchen</button></form><div class="list">@foreach($customers as $k)@php $l=$latest->get((int)$k->intID); @endphp<label class="item"><span><input type="radio" name="pick_customer" value="{{$k->intID}}"> {{$k->intID}}</span><span>{{trim($k->strName)}}</span><span>{{$l?date('d.m.Y H:i',strtotime($l->latest)):''}}</span></label>@endforeach</div>{{$customers->links()}}</div></div>
<p class="hint">Wie in Access werden nur Domains ohne Kundenzuordnung angezeigt. Die Zuordnung schreibt ausschließlich Kundennummer und Registrierungsdatum in tblDomains.</p></div>
<script>document.querySelectorAll('[name=pick_domain]').forEach(x=>x.addEventListener('change',()=>{domainId.value=x.value;domainName.value=x.dataset.name;registeredAt.value=x.dataset.date;}));document.querySelectorAll('[name=pick_customer]').forEach(x=>x.addEventListener('change',()=>{customerId.value=x.value;customerIdDisplay.value=x.value;}));</script><script src="{{asset('js/db-window-manager.js')}}"></script></body></html>
