<!DOCTYPE html>
<html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $title }}</title>
<style>
body{font:14px Arial;background:#d9d9d9;padding:12px;color:#111}.window{max-width:1100px;margin:auto;background:#efefef;border:1px solid #888;padding:18px}.toolbar{display:flex;justify-content:space-between;gap:12px;margin-bottom:12px;align-items:center}.toolbar-actions{display:flex;gap:7px;align-items:center;flex-wrap:wrap}.button{display:inline-block;padding:7px 12px;border:1px solid #777;background:#eee;color:#111;text-decoration:none;font:inherit;cursor:pointer}.button.pdf{background:#e6edf5;font-weight:bold}.searchbar{display:flex;gap:6px;align-items:center;margin-bottom:14px;padding:9px;background:#ddd;border:1px solid #aaa}.searchbar input{flex:1;min-width:180px;padding:7px;border:1px solid #888}.searchbar button{padding:7px 10px;border:1px solid #777;background:#eee;cursor:pointer}.search-count{min-width:72px;text-align:center;color:#555}.doc{background:#fff;border:1px solid #aaa;padding:22px;line-height:1.5}.doc h1,.doc h2,.doc h3{color:#0000aa}.doc table{width:100%;border-collapse:collapse}.doc th,.doc td{border:1px solid #aaa;padding:6px;text-align:left;vertical-align:top}.doc code{background:#eee;padding:1px 4px}.doc pre{background:#f5f5f5;border:1px solid #ccc;padding:10px;overflow:auto}.doc mark{background:#ffe66d;padding:0}.doc mark.active{outline:2px solid #c00;background:#ffc107}
@media print{body{background:#fff;padding:0}.window{max-width:none;border:0;background:#fff;padding:0}.toolbar,.searchbar{display:none!important}.doc{border:0;padding:0}.doc mark,.doc mark.active{background:transparent;outline:0}}
</style></head><body><div class="window">
<div class="toolbar"><div class="toolbar-actions"><a class="button" href="{{ route('dashboard') }}">← Hauptmenü</a><a class="button pdf" href="{{ $pdfUrl }}">PDF exportieren</a><button class="button" type="button" onclick="window.print()">Drucken</button></div><div><a href="{{ route('frontend.switch','modern') }}">Zum neuen Frontend wechseln →</a></div></div>
<div class="searchbar"><strong>Suchen:</strong><input id="doc-search" type="search" placeholder="Begriff eingeben..." autocomplete="off"><button type="button" id="search-prev">↑</button><button type="button" id="search-next">↓</button><span class="search-count" id="search-count">0 Treffer</span></div>
<div class="doc" id="doc-content">{!! $content !!}</div>
</div><script src="{{ asset('js/db-window-manager.js') }}?v=20260918-2"></script>
<script>
(()=>{const input=document.getElementById('doc-search'),root=document.getElementById('doc-content'),count=document.getElementById('search-count');let marks=[],current=-1;
const clear=()=>{root.querySelectorAll('mark[data-doc-search]').forEach(m=>m.replaceWith(document.createTextNode(m.textContent)));root.normalize();marks=[];current=-1;};
const show=i=>{if(!marks.length)return;marks.forEach(m=>m.classList.remove('active'));current=(i+marks.length)%marks.length;marks[current].classList.add('active');marks[current].scrollIntoView({behavior:'smooth',block:'center'});count.textContent=`${current+1} / ${marks.length}`;};
const search=()=>{clear();const q=input.value.trim();if(!q){count.textContent='0 Treffer';return;}const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement&& !['SCRIPT','STYLE','MARK'].includes(n.parentElement.tagName)&&n.nodeValue.toLocaleLowerCase('de').includes(q.toLocaleLowerCase('de'))?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const n of nodes){const text=n.nodeValue,low=text.toLocaleLowerCase('de'),needle=q.toLocaleLowerCase('de');let pos=0,idx,frag=document.createDocumentFragment();while((idx=low.indexOf(needle,pos))!==-1){frag.append(text.slice(pos,idx));const m=document.createElement('mark');m.dataset.docSearch='1';m.textContent=text.slice(idx,idx+q.length);frag.append(m);pos=idx+q.length;}frag.append(text.slice(pos));n.replaceWith(frag);}marks=[...root.querySelectorAll('mark[data-doc-search]')];count.textContent=marks.length?`1 / ${marks.length}`:'0 Treffer';if(marks.length)show(0);};
input.addEventListener('input',search);input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();show(current+(e.shiftKey?-1:1));}});document.getElementById('search-next').onclick=()=>show(current+1);document.getElementById('search-prev').onclick=()=>show(current-1);})();
</script></body></html>