<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Offene Rechnungen · {{ $kunde->strName }}</title>
<style>*{box-sizing:border-box}body{margin:0;font:14px Segoe UI,Arial;background:#f4f6f8;color:#1f2937}.page{max-width:1250px;margin:auto;padding:32px}.card{background:#fff;border-radius:12px;box-shadow:0 2px 8px #0001;padding:24px}a{color:#0369a1;text-decoration:none}table{width:100%;border-collapse:collapse;margin-top:16px}th,td{padding:10px 8px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}th{font-size:12px;text-transform:uppercase;color:#64748b}.money{text-align:right;white-space:nowrap}.badge{display:inline-block;padding:3px 7px;border-radius:999px;background:#fef3c7;color:#92400e;font-size:12px}.empty{padding:24px;background:#f8fafc;border-radius:8px;color:#64748b}</style></head><body><div class="page">
<a href="{{ route('kunden.show',$kunde->intID) }}">← {{ $kunde->strName }}</a><h1>Offene Rechnungen</h1><div class="card">
@if($rechnungen->isEmpty())<div class="empty">Keine offenen Rechnungen vorhanden.</div>@else
<table><thead><tr><th>Rechnung</th><th>Auftrag</th><th>Datum</th><th>Fällig</th><th>Empfänger</th><th>Netto</th><th>Steuer</th><th>Gesamt</th><th>Bezahlt</th><th>Mahnstufe</th><th>Status</th></tr></thead><tbody>
@foreach($rechnungen as $r)<tr>
<td><a href="{{ route('rechnungen.show',$r->intID) }}"><strong>{{ $r->intRechNr }}</strong></a></td><td>{{ $r->intAufNr }}</td><td>{{ $r->datRechnungsDatum ? date('d.m.Y',strtotime($r->datRechnungsDatum)) : '' }}</td><td>{{ $r->datFaelligkeitsDatum ? date('d.m.Y',strtotime($r->datFaelligkeitsDatum)) : '' }}</td><td>{{ $r->strKundenNameAufRechnung }}</td>
<td class="money">{{ number_format((float)$r->fBetrag,2,',','.') }} €</td><td class="money">{{ number_format((float)$r->fSteuer,2,',','.') }} €</td><td class="money"><strong>{{ number_format((float)$r->fRechnungsbetrag,2,',','.') }} €</strong></td><td class="money">{{ number_format((float)$r->fBezahlterBetrag,2,',','.') }} €</td><td>{{ $r->intMahnstufe ?? '-' }}</td>
<td>@if($r->bolRechnungStrittig)<span class="badge">Strittig</span>@elseif($r->intMahnstufe)<span class="badge">Mahnstufe {{ $r->intMahnstufe }}</span>@else<span style="color:#64748b">Offen</span>@endif</td>
</tr>@endforeach</tbody></table>@endif</div></div><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>