server {
    listen 127.0.0.1:8081;
    server_name db-webapp.topsnet-ads.tops.net;

    location ^~ /fakturierung {
        auth_gss on;
        auth_gss_keytab /etc/nginx/db-webapp-http.keytab;
        auth_gss_service_name HTTP/db-webapp.topsnet-ads.tops.net;
        auth_gss_allow_basic_fallback off;
        auth_gss_format_full on;

        auth_request /__authz_invoice;
        auth_request_set $invoice_access $upstream_http_x_db_webapp_rechnungstool;

        proxy_set_header X-Remote-User $remote_user;
        proxy_set_header X-DB-Webapp-Rechnungstool $invoice_access;
        proxy_set_header Authorization "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://127.0.0.1:8080;
    }

    location / {
        auth_gss on;
        auth_gss_keytab /etc/nginx/db-webapp-http.keytab;
        auth_gss_service_name HTTP/db-webapp.topsnet-ads.tops.net;
        auth_gss_allow_basic_fallback off;
        auth_gss_format_full on;

        auth_request /__authz_webapp;
        auth_request_set $invoice_access $upstream_http_x_db_webapp_rechnungstool;

        proxy_set_header X-Remote-User $remote_user;
        proxy_set_header X-DB-Webapp-Rechnungstool $invoice_access;
        proxy_set_header Authorization "";
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_pass http://127.0.0.1:8080;
    }

    location = /__authz_webapp {
        internal;
        proxy_pass http://127.0.0.1:8090/check?group=DB-Webapp-Users;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Remote-User $remote_user;
    }

    location = /__authz_invoice {
        internal;
        proxy_pass http://127.0.0.1:8090/check?group=DB-Webapp-Users&group=DB-Webapp-Rechnungstool;
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Remote-User $remote_user;
    }
}
