<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><title>{{ $produkt ? 'Produkt '.$produkt->intID : 'Neues Produkt' }}</title><style>
body{font:14px "Segoe UI",Arial;background:#f4f6f8;margin:0;color:#1f2937}.page{max-width:1100px;margin:auto;padding:28px}.card{background:white;border:1px solid #d7dce2;border-radius:12px;padding:24px;box-shadow:0 4px 18px #0001}.top{display:flex;justify-content:space-between;align-items:center}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px 26px}.field{display:grid;gap:6px}.field label{font-weight:600}.wide{grid-column:1/-1}input,select,textarea{width:100%;box-sizing:border-box;padding:9px;border:1px solid #b9c1cb;border-radius:7px;background:white}textarea{min-height:140px}.checks{display:flex;gap:28px}.checks input{width:auto}.button{display:inline-block;padding:9px 15px;border:1px solid #9aa3ae;border-radius:7px;background:#fff;color:#1f2937;text-decoration:none;cursor:pointer}.primary{background:#1f5f99;color:white;border-color:#1f5f99}.err{background:#fee2e2;padding:10px;border-radius:7px;margin-bottom:14px}.ok{background:#dcfce7;padding:10px;border-radius:7px;margin-bottom:14px}
</style></head><body>
<x-page-help title="Produkte">Hier werden Produktstammdaten und abrechnungsrelevante Zuordnungen gepflegt. Änderungen können spätere Aufträge, DATEV-Zuordnungen und Rechnungen beeinflussen.</x-page-help>
<div class="page"><div class="card"><div class="top"><h1>{{ $produkt ? 'Produkt '.$produkt->intID : 'Neues Produkt' }}</h1><a href="{{ route('frontend.switch','classic') }}">← Zur klassischen Ansicht</a></div>
@if(session('status'))<div class="ok">{{ session('status') }}</div>@endif @if($errors->any())<div class="err">{{ implode(' · ',$errors->all()) }}</div>@endif
<form method="post" action="{{ $produkt ? route('produkte.update',$produkt->intID) : route('produkte.store') }}">@csrf @if($produkt) @method('PUT') @endif
@include('produkte._fields')
<p><button class="button primary" type="submit">Speichern</button> <a class="button" href="{{ route('produkte.index') }}">Zur Produktliste</a></p></form></div></div><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>
