<!DOCTYPE html>
<html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $title }}</title>
<style>
*{box-sizing:border-box}body{margin:0;font:14px Segoe UI,Arial;background:#f4f6f8;color:#1f2937}.page{max-width:1150px;margin:auto;padding:32px}.toolbar{display:flex;justify-content:space-between;gap:12px;margin-bottom:14px;align-items:center}.toolbar-actions{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.button{display:inline-block;padding:9px 13px;border:0;border-radius:7px;background:#0069c2;color:#fff;text-decoration:none;font:inherit;cursor:pointer}.button.secondary{background:#e2e8f0;color:#0f172a}.button.pdf{background:#0f766e}.searchbar{display:flex;gap:8px;align-items:center;margin-bottom:16px;padding:12px;background:#fff;border-radius:10px;box-shadow:0 2px 8px #0001}.searchbar input{flex:1;min-width:180px;padding:9px 10px;border:1px solid #cbd5e1;border-radius:7px}.searchbar button{padding:9px 11px;border:1px solid #cbd5e1;border-radius:7px;background:#f8fafc;cursor:pointer}.search-count{min-width:76px;text-align:center;color:#64748b}.doc{background:#fff;border-radius:12px;box-shadow:0 2px 8px #0001;padding:28px;line-height:1.6}.doc h1,.doc h2,.doc h3{color:#0f172a}.doc table{width:100%;border-collapse:collapse}.doc th,.doc td{padding:9px;border-bottom:1px solid #e5e7eb;text-align:left;vertical-align:top}.doc code{background:#f1f5f9;padding:1px 4px;border-radius:4px}.doc pre{background:#f8fafc;padding:12px;border-radius:8px;overflow:auto}.doc mark{background:#fde68a;padding:0}.doc mark.active{outline:2px solid #dc2626;background:#fbbf24}
@media print{body{background:#fff}.page{max-width:none;padding:0}.toolbar,.searchbar{display:none!important}.doc{box-shadow:none;border-radius:0;padding:0}.doc mark,.doc mark.active{background:transparent;outline:0}}
</style></head><body><div class="page">
<div class="toolbar"><div class="toolbar-actions"><a class="button" href="{{ route('dashboard') }}">← Hauptmenü</a><a class="button pdf" href="{{ $pdfUrl }}">PDF exportieren</a><button class="button secondary" type="button" onclick="window.print()">Drucken</button></div><a href="{{ route('frontend.switch','classic') }}">← Zur klassischen Ansicht</a></div>
<div class="searchbar"><strong>Suchen:</strong><input id="doc-search" type="search" placeholder="Begriff eingeben..." autocomplete="off"><button type="button" id="search-prev">↑</button><button type="button" id="search-next">↓</button><span class="search-count" id="search-count">0 Treffer</span></div>
<div class="doc" id="doc-content">{!! $content !!}</div>
</div><script src="{{ asset('js/db-window-manager.js') }}?v=20260918-2"></script>
<script>
(()=>{const input=document.getElementById('doc-search'),root=document.getElementById('doc-content'),count=document.getElementById('search-count');let marks=[],current=-1;
const clear=()=>{root.querySelectorAll('mark[data-doc-search]').forEach(m=>m.replaceWith(document.createTextNode(m.textContent)));root.normalize();marks=[];current=-1;};
const show=i=>{if(!marks.length)return;marks.forEach(m=>m.classList.remove('active'));current=(i+marks.length)%marks.length;marks[current].classList.add('active');marks[current].scrollIntoView({behavior:'smooth',block:'center'});count.textContent=`${current+1} / ${marks.length}`;};
const search=()=>{clear();const q=input.value.trim();if(!q){count.textContent='0 Treffer';return;}const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement&&!['SCRIPT','STYLE','MARK'].includes(n.parentElement.tagName)&&n.nodeValue.toLocaleLowerCase('de').includes(q.toLocaleLowerCase('de'))?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const n of nodes){const text=n.nodeValue,low=text.toLocaleLowerCase('de'),needle=q.toLocaleLowerCase('de');let pos=0,idx,frag=document.createDocumentFragment();while((idx=low.indexOf(needle,pos))!==-1){frag.append(text.slice(pos,idx));const m=document.createElement('mark');m.dataset.docSearch='1';m.textContent=text.slice(idx,idx+q.length);frag.append(m);pos=idx+q.length;}frag.append(text.slice(pos));n.replaceWith(frag);}marks=[...root.querySelectorAll('mark[data-doc-search]')];count.textContent=marks.length?`1 / ${marks.length}`:'0 Treffer';if(marks.length)show(0);};
input.addEventListener('input',search);input.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();show(current+(e.shiftKey?-1:1));}});document.getElementById('search-next').onclick=()=>show(current+1);document.getElementById('search-prev').onclick=()=>show(current-1);})();
</script></body></html>