<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Anbindungen</title><style>
body{font:13px Arial;background:#d9d9d9;padding:12px}.window{max-width:1400px;margin:auto;background:#efefef;border:1px solid #888;padding:14px}.top{display:flex;justify-content:space-between;align-items:center}.button{display:inline-block;padding:7px 12px;border:1px solid #777;background:#eee;color:#111;text-decoration:none;cursor:pointer}form.search{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:12px 0}input,select{padding:6px;border:1px solid #999;background:#fff}table{width:100%;border-collapse:collapse;background:#fff}th,td{border:1px solid #aaa;padding:5px;vertical-align:top}th{background:#ddd}.muted{color:#666}.pager{display:flex;gap:8px;align-items:center;margin-top:12px}</style></head><body><div class="window">
<div class="top"><h2>Anbindungen</h2><a href="{{ route('frontend.switch','modern') }}">Zum neuen Frontend wechseln →</a></div>
<p><a class="button" href="{{ route('anbindungen.create') }}">Neue Anbindung</a> <a class="button" href="{{ route('dashboard') }}">Schließen</a></p>
<form class="search" method="get"><label>Suchen <input name="q" value="{{ $q }}" placeholder="ID, Referenz, Auftrag, Position, Kunde, Rechnungsinfo"></label><label>Accounting-Art <select name="typ"><option value="0">alle</option>@foreach($types as $k=>$label)<option value="{{ $k }}" @selected($type===$k)>{{ $k }} · {{ $label }}</option>@endforeach</select></label><button class="button">Suchen</button></form>
<table><thead><tr><th>ID</th><th>Art</th><th>Referenz</th><th>Technische Information</th><th>Kunde</th><th>Auftrag / Position</th><th>Abrechenbar</th><th>Zeitraum</th><th></th></tr></thead><tbody>
@forelse($anbindungen as $a)<tr><td>{{ $a->intID }}</td><td>{{ $types[(int)$a->intTyp] ?? 'Typ '.$a->intTyp }}</td><td>{{ $a->intAnbindungReferenz }}</td><td>@if($a->referenzInfo)<strong>{{ $a->referenzInfo['title'] }}</strong><br><span class="muted">{{ $a->referenzInfo['detail'] }}</span>@else<span class="muted">keine Referenzinformation</span>@endif</td><td>#{{ $a->auftragKID }}<br>{{ $a->kunde->strName ?? '' }}</td><td>{{ $a->intAufNr }} / {{ $a->intAuftragsPos }}</td><td>{{ $a->boolAbrechenbar ? 'Ja':'Nein' }}</td><td>{{ date('d.m.Y H:i:s',strtotime($a->dateAbrechenbarStart)) }}<br>bis {{ date('d.m.Y H:i:s',strtotime($a->dateAbrechenbarEnde)) }}</td><td><a class="button" href="{{ route('anbindungen.edit',$a->intID) }}">Öffnen</a></td></tr>@empty<tr><td colspan="9">Keine Anbindungen gefunden.</td></tr>@endforelse
</tbody></table>
<div class="pager">@if($anbindungen->previousPageUrl())<a class="button" href="{{ $anbindungen->previousPageUrl() }}">← Zurück</a>@endif <span>Seite {{ $anbindungen->currentPage() }} von {{ $anbindungen->lastPage() }} · {{ $anbindungen->total() }} Treffer</span> @if($anbindungen->nextPageUrl())<a class="button" href="{{ $anbindungen->nextPageUrl() }}">Weiter →</a>@endif</div>
</div><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>
