<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $id ? 'Anbindung '.$id : 'Neue Anbindung' }}</title><style>body{font:13px Arial;background:#d9d9d9;padding:12px}.window{max-width:1050px;margin:auto;background:#efefef;border:1px solid #888;padding:14px}.button{display:inline-block;padding:7px 12px;border:1px solid #777;background:#eee;color:#111;text-decoration:none}table{width:100%;border-collapse:collapse;background:#fff;margin-top:10px}th,td{border:1px solid #aaa;padding:6px;vertical-align:top}th{background:#ddd}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 24px}.field{display:grid;grid-template-columns:180px 1fr;gap:8px;align-items:center}input,select,textarea{width:100%;padding:5px;border:1px solid #999}textarea{min-height:90px}.info{background:#fff;border:1px solid #aaa;padding:8px}.err{background:#fee;border:1px solid #b91c1c;padding:8px}</style></head><body><div class="window">
<div style="text-align:right"><a href="{{ route('frontend.switch', 'modern') }}">Zum neuen Frontend wechseln →</a></div>
<h2>{{ $id ? 'Anbindung '.$id.' bearbeiten' : 'Neue Anbindung' }}</h2><p>Auftrag {{ $auftrag->intAufNr }} · Position {{ $position->intID }} · Kunde #{{ $kunde->intID }} {{ $kunde->strName }}</p>
@if(session('status'))<div class="info">{{ session('status') }}</div>@endif @if($errors->any())<div class="err">{{ implode(' · ',$errors->all()) }}</div>@endif
@if($readOnlyAltbestand)<div class="info"><strong>SMS-Altbestand:</strong> Diese Verknüpfung wird nur angezeigt und nicht mehr bearbeitet.</div>@endif
<form method="post" action="{{ $id ? route('kunden.auftraege.positionen.anbindungen.update',[$kunde->intID,$auftrag->intAufNr,$position->intID,$id]) : route('kunden.auftraege.positionen.anbindungen.store',[$kunde->intID,$auftrag->intAufNr,$position->intID]) }}">@csrf @if($id) @method('PUT') @endif
<div class="grid"><div class="field"><label>Art des Accountings</label><select id="typeSelect" name="intTyp" required @disabled($readOnlyAltbestand)>@foreach($types as $key=>$label) @if(!$id && in_array($key,[4,7])) @continue @endif<option value="{{ $key }}" @selected(old('intTyp',$anbindung->intTyp)==$key)>{{ $label }}</option>@endforeach</select></div>
<div class="field"><label>Anbindungs-Referenz</label><input id="refInput" type="number" min="0" name="intAnbindungReferenz" value="{{ old('intAnbindungReferenz',$anbindung->intAnbindungReferenz) }}" required @disabled($readOnlyAltbestand)><div style="font-size:12px;margin-top:4px">ID eingeben oder über die Vorschläge nach Name/Bezeichnung suchen.</div>@foreach($referenceOptions as $type=>$items)<datalist id="refs-{{ $type }}">@foreach($items as $item)<option value="{{ $item['id'] }}">{{ $item['label'] }}</option>@endforeach</datalist>@endforeach</div>
<div class="field"><label>Abrechenbar?</label><label style="display:flex;gap:8px;align-items:center"><input style="width:auto" type="checkbox" name="boolAbrechenbar" value="1" @checked(old('boolAbrechenbar',$anbindung->boolAbrechenbar))> Ja</label></div><div></div>
<div class="field"><label>Startdatum der Abrechnung</label><input type="date" name="dateAbrechenbarStart" value="{{ old('dateAbrechenbarStart',date('Y-m-d',strtotime($anbindung->dateAbrechenbarStart))) }}" required></div>
<div class="field"><label>Enddatum der Abrechnung</label><input type="date" name="dateAbrechenbarEnde" value="{{ old('dateAbrechenbarEnde',date('Y-m-d',strtotime($anbindung->dateAbrechenbarEnde))) }}" required></div>
<div class="field" style="grid-column:1/-1"><label>Kopie der Rechnungsinfo</label><textarea name="strKopieRechnungsinfo">{{ old('strKopieRechnungsinfo',$anbindung->strKopieRechnungsinfo ?? '') }}</textarea></div></div>
@if($referenzInfo)<h3>Informationen der Referenz</h3><div class="info"><strong>{{ $referenzInfo['title'] }}</strong><br>{{ $referenzInfo['detail'] }}<br><br>{!! nl2br(e(trim($referenzInfo['rechnung'] ?? ''))) !!}</div>@endif
<p style="font-size:12px">Die technischen Daten der Referenz sind hier absichtlich nicht editierbar. Bei Dialin werden keine Kennwörter angezeigt.</p>
<p>@unless($readOnlyAltbestand)<button class="button" type="submit">Anbindung speichern</button>@endunless <a class="button" href="{{ route('kunden.auftraege.positionen.anbindungen.index',[$kunde->intID,$auftrag->intAufNr,$position->intID]) }}">Zur Liste</a></p></form><script>function setRefList(){const t=document.getElementById('typeSelect');const r=document.getElementById('refInput');if(t&&r){const id='refs-'+t.value;r.setAttribute('list',document.getElementById(id)?id:'');}}document.getElementById('typeSelect')?.addEventListener('change',setRefList);setRefList();</script></div><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>