<!DOCTYPE html>
<html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $id ? 'Anbindung '.$id : 'Neue Anbindung' }}</title>
<style>
body{font:13px Arial;background:#d9d9d9;margin:0;padding:12px;color:#111}.window{max-width:1030px;margin:auto;background:#ece9d8;border:1px solid #777;box-shadow:2px 2px 5px #0003;padding:12px}.top{display:flex;justify-content:space-between;align-items:center}.top h2{margin:0 0 10px;font-size:18px}.formbox{border:1px solid #9b9b9b;background:#f4f1e3;padding:12px}.row{display:grid;grid-template-columns:190px minmax(260px,1fr) 170px minmax(210px,.75fr);gap:7px 9px;align-items:center;margin-bottom:7px}.row.one{grid-template-columns:190px 1fr}.label{font-weight:normal}.button{display:inline-block;padding:6px 13px;border:1px solid #777;background:#efefef;color:#111;text-decoration:none;cursor:pointer;box-shadow:inset 1px 1px #fff}.button:hover{background:#fff}input,select,textarea{box-sizing:border-box;width:100%;padding:5px;border:1px solid #777;background:#fff;font:13px Arial}textarea{min-height:62px;resize:vertical}.readonly-filter{box-sizing:border-box;width:100%;min-height:27px;padding:5px 24px 5px 6px;border:1px solid #777;background:#d7d7d7;position:relative;cursor:context-menu;white-space:pre-wrap;overflow-wrap:anywhere}.readonly-filter:after{content:'▾';position:absolute;right:6px;top:4px;color:#555;font-size:12px}.readonly-filter:focus{outline:1px dotted #000;outline-offset:-3px}.hint{font-size:11px;color:#555}.info{margin:10px 0;padding:8px;border:1px solid #999;background:#fff}.subform{border:1px solid #888;background:#fff;padding:8px;min-height:70px}.subform-title{font-weight:bold;margin-bottom:5px}.err{background:#fee;border:1px solid #b91c1c;padding:8px;margin-bottom:8px}.ok{background:#e8f6e8;border:1px solid #4b8b4b;padding:8px;margin-bottom:8px}.actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:11px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #aaa;padding:4px}th{background:#ddd;text-align:left}.ctx{display:none;position:fixed;z-index:9999;width:210px;background:#f4f4f4;border:1px solid #777;box-shadow:2px 2px 6px #0004;padding:3px}.ctx button{display:block;width:100%;border:0;background:transparent;text-align:left;padding:5px 8px;font:13px Arial;cursor:pointer}.ctx button:hover{background:#0a64ad;color:#fff}.ctx hr{border:0;border-top:1px solid #aaa;margin:3px}.filter-note{font-size:11px;color:#555;margin-top:4px}@media(max-width:800px){.row{grid-template-columns:150px 1fr}.row>*:nth-child(3){grid-column:1}.row>*:nth-child(4){grid-column:2}}
</style></head><body><div class="window">
<div class="top"><h2>Anbindungen</h2><a href="{{ route('frontend.switch','modern') }}">Zum neuen Frontend wechseln →</a></div>
@if(session('status'))<div class="ok">{{ session('status') }}</div>@endif
@if($errors->any())<div class="err">{{ implode(' · ',$errors->all()) }}</div>@endif
<form method="post" action="{{ $id ? route('anbindungen.update',$id) : route('anbindungen.store') }}">@csrf @if($id)@method('PUT')@endif
<div class="formbox"><div class="row"><span class="label">Anbindungs-ID</span>@if($id)<div class="readonly-filter" tabindex="0" data-filter-field="id" data-filter-value="{{ $id }}">{{ $id }}</div>@else<div class="readonly-filter" style="cursor:default">(neu)</div>@endif<span class="label">AnbindungsReferenz</span><input id="refInput" type="number" min="0" name="intAnbindungReferenz" value="{{ old('intAnbindungReferenz',$anbindung->intAnbindungReferenz) }}" required></div>
<div class="row"><span class="label">Art des Accountings</span><select id="typeSelect" name="intTyp" required>@foreach($types as $k=>$label)<option value="{{ $k }}" @selected((int)old('intTyp',$anbindung->intTyp)===$k)>{{ $label }}</option>@endforeach</select><span></span><span></span></div>
@if($referenzInfo)<div class="row one"><span class="label">Informationen über das Accounting</span><div class="subform"><div class="subform-title">{{ $referenzInfo['title'] }}</div><div>{{ $referenzInfo['detail'] }}</div>@if(!empty($referenzInfo['rechnung']))<div style="margin-top:6px">{!! nl2br(e(trim($referenzInfo['rechnung']))) !!}</div>@endif</div></div>@endif
@if(($referenzInfo['kind'] ?? '')==='fremd' && !empty($referenzInfo['rows']))<div class="row one"><span></span><div><table><thead><tr><th>Monat</th><th>Jahr</th><th>MB rein</th><th>MB raus</th><th>Gesamt</th><th>Dauer sec</th><th>Rechnungsinfo</th></tr></thead><tbody>@foreach($referenzInfo['rows'] as $r)<tr><td>{{ $r->intMonat }}</td><td>{{ $r->intJahr }}</td><td>{{ $r->decMBin }}</td><td>{{ $r->decMBout }}</td><td>{{ $r->decGesamt }}</td><td>{{ $r->intVerbindungsdauerInSec }}</td><td>{{ $r->strrechnungsinfo }}</td></tr>@endforeach</tbody></table></div></div>@endif
<div class="row"><span class="label">Abrechenbar?</span><label><input style="width:auto" type="checkbox" name="boolAbrechenbar" value="1" @checked(old('boolAbrechenbar',$anbindung->boolAbrechenbar))> Ja</label><span></span><span></span></div>
<div class="row"><span class="label">Startdatum der Abrechnung</span><input type="datetime-local" step="1" name="dateAbrechenbarStart" value="{{ old('dateAbrechenbarStart',date('Y-m-d\\TH:i:s',strtotime($anbindung->dateAbrechenbarStart))) }}" required><span class="label">Enddatum der Abrechnung</span><input type="datetime-local" step="1" name="dateAbrechenbarEnde" value="{{ old('dateAbrechenbarEnde',date('Y-m-d\\TH:i:s',strtotime($anbindung->dateAbrechenbarEnde))) }}" required></div>
<div class="row one"><span class="label">Kopie der Rechnungsinfo</span><div><div class="readonly-filter" tabindex="0" data-filter-field="invoice_info" data-filter-value="{{ old('strKopieRechnungsinfo',$anbindung->strKopieRechnungsinfo ?? '') }}">{{ old('strKopieRechnungsinfo',$anbindung->strKopieRechnungsinfo ?? '') }}</div><input type="hidden" name="strKopieRechnungsinfo" value="{{ old('strKopieRechnungsinfo',$anbindung->strKopieRechnungsinfo ?? '') }}"></div></div>
<div class="hint" style="margin:2px 0 10px 199px">Die technischen Informationen sind wie in Access nicht direkt editierbar.</div>
@if($id && $position && $auftrag && $kunde)
<div class="row"><span class="label">Kundennummer</span><div class="readonly-filter" tabindex="0" data-filter-field="customer_id" data-filter-value="{{ $kunde->intID }}">{{ $kunde->intID }}</div><span class="label">Kundenname</span><div class="readonly-filter" tabindex="0" data-filter-field="customer_name" data-filter-value="{{ $kunde->strName }}">{{ $kunde->strName }}</div></div>
<div class="row"><span class="label">ID der Auftragsposition</span><div class="readonly-filter" tabindex="0" data-filter-field="position_id" data-filter-value="{{ $position->intID }}">{{ $position->intID }}</div><span class="label">ID des Auftrags</span><div class="readonly-filter" tabindex="0" data-filter-field="order_id" data-filter-value="{{ $auftrag->intAufNr }}">{{ $auftrag->intAufNr }}</div></div>
<input type="hidden" name="intAuftragsPos" value="{{ $position->intID }}">
@else
<div class="row"><span class="label">ID der Auftragsposition</span><input type="number" min="1" name="intAuftragsPos" value="{{ old('intAuftragsPos',$anbindung->intAuftragsPos ?? '') }}" required><span></span><span></span></div>
@endif
<div class="filter-note">Graue Felder: Rechtsklick oder Doppelklick öffnet den Access-artigen Textfilter.</div>
</div>
@foreach($referenceOptions as $typeKey=>$items)<datalist id="refs-{{ $typeKey }}">@foreach($items as $item)<option value="{{ $item['id'] }}">{{ $item['label'] }}</option>@endforeach</datalist>@endforeach<div class="actions"><button class="button" type="submit">Speichern</button><a class="button" href="{{ route('anbindungen.index') }}">Schließen</a>@if($kunde)<a class="button" href="{{ route('kunden.show',$kunde->intID) }}">Kundenformular</a>@endif @if($kunde && $auftrag)<a class="button" href="{{ route('kunden.auftraege.show',[$kunde->intID,$auftrag->intAufNr]) }}">Auftrag öffnen</a>@endif</div>
</form></div>
<div id="filterMenu" class="ctx" role="menu"><button data-op="equals">Gleich…</button><button data-op="not_equals">Nicht gleich…</button><hr><button data-op="starts">Beginnt mit…</button><button data-op="not_starts">Beginnt nicht mit…</button><button data-op="contains">Enthält…</button><button data-op="not_contains">Enthält nicht…</button><button data-op="ends">Endet mit…</button><button data-op="not_ends">Endet nicht mit…</button><hr><button data-clear="1">Alle Filter entfernen</button></div>
<script>
function refs(){const t=document.getElementById('typeSelect'),r=document.getElementById('refInput');if(!t||!r)return;const d=document.getElementById('refs-'+t.value);d?r.setAttribute('list',d.id):r.removeAttribute('list')}
document.getElementById('typeSelect')?.addEventListener('change',refs);refs();
const menu=document.getElementById('filterMenu');let target=null;
function openFilter(e,el){e.preventDefault();target=el;menu.style.display='block';menu.style.left=Math.min(e.clientX,window.innerWidth-225)+'px';menu.style.top=Math.min(e.clientY,window.innerHeight-280)+'px';}
document.querySelectorAll('.readonly-filter[data-filter-field]').forEach(el=>{el.addEventListener('contextmenu',e=>openFilter(e,el));el.addEventListener('dblclick',e=>openFilter(e,el));});
document.addEventListener('click',e=>{if(!menu.contains(e.target))menu.style.display='none'});
menu.querySelectorAll('button[data-op]').forEach(btn=>btn.addEventListener('click',()=>{if(!target)return;const v=prompt('Filterwert:',target.dataset.filterValue||target.textContent.trim());if(v===null||v==='')return;const u=new URL('{{ route('anbindungen.index') }}',window.location.origin);u.searchParams.set('f_field',target.dataset.filterField);u.searchParams.set('f_op',btn.dataset.op);u.searchParams.set('f_value',v);window.location=u.toString();}));
menu.querySelector('button[data-clear]').addEventListener('click',()=>window.location='{{ route('anbindungen.index') }}');
</script><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>