<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Anbindungen · Position {{ $position->intID }}</title><style>body{font:13px Arial;background:#d9d9d9;padding:12px}.window{max-width:1050px;margin:auto;background:#efefef;border:1px solid #888;padding:14px}.button{display:inline-block;padding:7px 12px;border:1px solid #777;background:#eee;color:#111;text-decoration:none}table{width:100%;border-collapse:collapse;background:#fff;margin-top:10px}th,td{border:1px solid #aaa;padding:6px;vertical-align:top}th{background:#ddd}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 24px}.field{display:grid;grid-template-columns:180px 1fr;gap:8px;align-items:center}input,select,textarea{width:100%;padding:5px;border:1px solid #999}textarea{min-height:90px}.info{background:#fff;border:1px solid #aaa;padding:8px}.err{background:#fee;border:1px solid #b91c1c;padding:8px}</style></head><body>
<x-page-help title="Verbindungen / Anbindungen">Hier werden technische Anbindungen und Accounting-Zuordnungen gepflegt. Änderungen können Erfassung und spätere Abrechnung beeinflussen. Vor dem Speichern Ziel, Kunde und Zuordnung prüfen.</x-page-help>
<div class="window">
<div style="text-align:right"><a href="{{ route('frontend.switch', 'modern') }}">Zum neuen Frontend wechseln →</a></div>
<h2>Anbindungen · Auftrag {{ $auftrag->intAufNr }} · Position {{ $position->intID }}</h2>
<p><a class="button" href="{{ route('kunden.auftraege.positionen.anbindungen.create',[$kunde->intID,$auftrag->intAufNr,$position->intID]) }}">Neue Anbindung</a></p>
@if($anbindungen->isEmpty())<p>Keine Anbindungen vorhanden.</p>@else
<table><thead><tr><th>ID</th><th>Art</th><th>Referenz</th><th>Information</th><th>Abrechenbar</th><th>Zeitraum</th><th></th></tr></thead><tbody>
@foreach($anbindungen as $a)<tr><td>{{ $a->intID }}</td><td>{{ $types[(int)$a->intTyp] ?? 'Typ '.$a->intTyp }}</td><td>{{ $a->intAnbindungReferenz }}</td><td>@if($a->referenzInfo)<strong>{{ $a->referenzInfo['title'] }}</strong><br>{{ $a->referenzInfo['detail'] }}@else{!! nl2br(e(trim($a->strKopieRechnungsinfo ?? ''))) !!}@endif</td><td>{{ $a->boolAbrechenbar ? 'Ja':'Nein' }}</td><td>{{ date('d.m.Y',strtotime($a->dateAbrechenbarStart)) }} – {{ date('d.m.Y',strtotime($a->dateAbrechenbarEnde)) }}</td><td><a class="button" href="{{ route('kunden.auftraege.positionen.anbindungen.edit',[$kunde->intID,$auftrag->intAufNr,$position->intID,$a->intID]) }}">Öffnen</a></td></tr>@endforeach
</tbody></table>@endif
<p><a class="button" href="{{ route('kunden.auftraege.show',[$kunde->intID,$auftrag->intAufNr]) }}">Zurück zum Auftrag</a></p></div><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>