<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Verbindung {{ $profile->exists?'bearbeiten':'anlegen' }}</title>
<style>body{font-family:system-ui,Segoe UI,Arial;background:#f3f6fa;color:#172033}.page{max-width:850px;margin:25px auto}.card{background:white;border:1px solid #dfe5ee;border-radius:13px;padding:22px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.field{display:flex;flex-direction:column;gap:5px}.wide{grid-column:1/-1}input,select,textarea{font:inherit;padding:10px;border:1px solid #ccd3df;border-radius:8px}textarea{min-height:100px}.btn{border:0;border-radius:8px;background:#1f4f8a;color:#fff;padding:10px 16px;font-weight:700;cursor:pointer}.errors{background:#fff0ee;padding:10px;border-radius:8px;margin-bottom:12px}.muted{color:#667085;font-size:12px}</style></head><body><main class="page"><p><a href="{{ route('admin.index') }}">← Administration</a></p><section class="card"><h1>Verbindung {{ $profile->exists?'bearbeiten':'anlegen' }}</h1>
@if($errors->any())<div class="errors"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ $profile->exists?route('admin.connections.update',$profile):route('admin.connections.store') }}">@csrf @if($profile->exists)@method('put')@endif
<div class="grid"><label class="field">Name<input name="name" required value="{{ old('name',$profile->name) }}"></label><label class="field">Technischer Schlüssel<input name="key" required pattern="[a-z0-9._-]+" value="{{ old('key',$profile->key) }}"><span class="muted">z. B. sql.accountings, smtp.primary oder storage.midas</span></label>
<label class="field">Typ<select name="type" required>@foreach(['sqlserver'=>'SQL Server','postgres'=>'PostgreSQL','smtp'=>'SMTP','filesystem'=>'Dateisystem','http'=>'HTTP/HTTPS'] as $value=>$label)<option value="{{ $value }}" @selected(old('type',$profile->type)===$value)>{{ $label }}</option>@endforeach</select></label><label class="field">Aktiv<label><input type="checkbox" name="active" value="1" @checked(old('active',$profile->active))> für spätere Systemzuordnung freigegeben</label></label>
<label class="field wide">Host, URL oder Verzeichnispfad<input name="host" value="{{ old('host',$profile->host) }}" placeholder="10.79.160.38, https://… oder /mnt/…"></label><label class="field">Port<input type="number" min="1" max="65535" name="port" value="{{ old('port',$profile->port) }}"></label><label class="field">Datenbank<input name="database" value="{{ old('database',$profile->database) }}"></label>
<label class="field">Benutzername<input name="username" autocomplete="off" value="{{ old('username',$profile->username) }}"></label><label class="field">Passwort / Secret<input type="password" name="secret" autocomplete="new-password" placeholder="{{ $profile->exists?'leer lassen = unverändert':'' }}"></label>
<label class="field">Dateisystem-Modus<select name="filesystem_mode"><option value="read-only" @selected(old('filesystem_mode',$profile->options['mode']??'read-only')==='read-only')>Nur lesen</option><option value="read-write" @selected(old('filesystem_mode',$profile->options['mode']??'')==='read-write')>Lesen und schreiben</option></select></label>
<label class="field">UNC-Zielpfad<input name="unc_root" value="{{ old('unc_root',$profile->options['unc_root']??'') }}" placeholder="\\\\server\\freigabe"></label>
<label class="field wide">Dateinamenschema<input name="filename_pattern" value="{{ old('filename_pattern',$profile->options['filename_pattern']??'') }}" placeholder="{year}/Rechnungen/Papier/{invoice_number}.pdf"><span class="muted">Platzhalter: {year} und {invoice_number}. Nur für die schreibbare Rechnungsablage.</span></label>
<label class="field wide">Weitere Optionen als JSON<textarea name="options_text" placeholder='{"tls":true,"verify_tls":true}'>{{ old('options_text',$profile->options ? json_encode($profile->options,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) : '') }}</textarea></label></div>
<p><button class="btn">Speichern</button></p></form></section></main></body></html>
