<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Administration</title>
<style>body{font-family:system-ui,Segoe UI,Arial;background:#f3f6fa;color:#172033;margin:0}.page{max-width:1450px;margin:auto;padding:28px}.top,.head{display:flex;justify-content:space-between;align-items:center;gap:15px}.card{background:#fff;border:1px solid #dfe5ee;border-radius:13px;margin-top:16px;padding:18px;box-shadow:0 3px 14px #1f29370c}h1,h2{margin:0}.btn{display:inline-block;border:0;border-radius:8px;background:#1f4f8a;color:#fff;padding:10px 15px;text-decoration:none;font-weight:700;cursor:pointer}.btn.gray{background:#526071}.btn.small{padding:6px 10px;font-size:12px}table{width:100%;border-collapse:collapse;margin-top:12px}th,td{text-align:left;padding:9px;border-bottom:1px solid #e7ebf1;vertical-align:top}.muted{color:#667085;font-size:12px}.ok{color:#176b3a}.error{color:#b42318}.flash{padding:10px 12px;border-radius:8px;margin-top:12px;background:#e8f7ee}.flash.error{background:#fff0ee}.actions{display:flex;gap:6px;flex-wrap:wrap}</style></head><body><main class="page">
<div class="top"><div><h1>Administration</h1><div class="muted">Geschützter Bereich für Verbindungen, Systemstatus und Logs</div></div><a href="{{ route('dashboard') }}">← Hauptmenü</a></div>
@if(session('status'))<div class="flash">{{ session('status') }}</div>@endif @if(session('error'))<div class="flash error">{{ session('error') }}</div>@endif
<section class="card"><div class="head"><div><h2>Verbindungen</h2><div class="muted">Zugangsdaten werden mit dem Laravel-Anwendungsschlüssel verschlüsselt gespeichert.</div></div><a class="btn" href="{{ route('admin.connections.create') }}">Neue Verbindung</a></div>
<table><thead><tr><th>Name / Schlüssel</th><th>Typ</th><th>Ziel</th><th>Aktiv</th><th>Letzter Test</th><th>Aktionen</th></tr></thead><tbody>
@forelse($profiles as $profile)<tr><td><strong>{{ $profile->name }}</strong><div class="muted">{{ $profile->key }} · geändert von {{ $profile->updated_by ?: '–' }}</div></td><td>{{ strtoupper($profile->type) }}</td><td>{{ $profile->host ?: '–' }}@if($profile->port):{{ $profile->port }}@endif @if($profile->database)<div class="muted">{{ $profile->database }}</div>@endif</td><td>{{ $profile->active ? 'Ja' : 'Nein' }}</td><td class="{{ $profile->last_test_status === 'ok' ? 'ok' : ($profile->last_test_status === 'error' ? 'error' : '') }}">{{ $profile->last_test_at?->format('d.m.Y H:i') ?: 'nicht getestet' }}<div class="muted">{{ $profile->last_test_message }}</div></td><td><div class="actions"><a class="btn gray small" href="{{ route('admin.connections.edit',$profile) }}">Bearbeiten</a><form method="post" action="{{ route('admin.connections.test',$profile) }}">@csrf<button class="btn small">Erreichbarkeit testen</button></form>@if($profile->type==='smtp')<form method="post" action="{{ route('admin.connections.test-mail',$profile) }}" onsubmit="return confirm('Testmail wirklich an '+this.recipient.value+' senden?')">@csrf<input type="email" name="recipient" value="sw@tops.net" required style="padding:6px;width:170px"><button class="btn small">Testmail senden</button></form>@endif</div></td></tr>
@empty<tr><td colspan="6">Noch keine administrativen Verbindungen hinterlegt.</td></tr>@endforelse
</tbody></table></section>
<section class="card"><h2>Anwendungslogs</h2><table><thead><tr><th>Datei</th><th>Größe</th><th>Geändert</th><th></th></tr></thead><tbody>@forelse($logFiles as $log)<tr><td>{{ $log['name'] }}</td><td>{{ number_format($log['size']/1024,1,',','.') }} KB</td><td>{{ date('d.m.Y H:i',$log['modified']) }}</td><td><a class="btn gray small" href="{{ route('admin.logs.show',$log['name']) }}">Letzte 500 Zeilen</a></td></tr>@empty<tr><td colspan="4">Keine Logs vorhanden.</td></tr>@endforelse</tbody></table></section>
<section class="card"><h2>Weitere administrative Aufgaben</h2><p class="muted">SMTP-Mailversand und MIDAS-Ablage werden über die Verbindungsprofile verwaltet. Wartungsmodus, Cache-/Schedulerstatus und weitere Betriebsfunktionen werden hier schrittweise ergänzt.</p></section>
</main></body></html>
