<!doctype html><html lang="de"><head><meta charset="utf-8"><title>IPv4 Reverse</title><style>
body{font:12px Tahoma,Arial;background:#d4d0c8;margin:0;padding:14px;color:#111}.window{max-width:760px;margin:auto}.top{display:flex;justify-content:space-between;align-items:center}.button{display:inline-block;padding:6px 10px;border:1px solid #777;background:#eee;color:#111;text-decoration:none}.notice{border:1px solid #888;background:#eee;padding:8px;margin:10px 0}.search{display:flex;gap:6px;align-items:end;margin:10px 0}.search label{display:grid;gap:3px}.search input{padding:5px;border:1px solid #888}.tbl{width:100%;border-collapse:collapse;background:#fff}.tbl th,.tbl td{border:1px solid #aaa;padding:6px;text-align:left}.tbl th{background:#ddd}.pager{margin-top:8px}</style></head><body>
<x-page-help title="IPv4 Reverse">Hier werden Reverse-DNS-Einträge für IPv4 verwaltet. Änderungen wirken auf technische DNS-Zuordnungen. IP-Adresse und Zielname vor dem Speichern prüfen.</x-page-help>
<div class="window">
<div class="top"><h2>IPv4 Reverse</h2><a href="{{ route('frontend.switch','modern') }}">Zum neuen Frontend wechseln →</a></div>
<div class="notice"><b>Nur Anzeige.</b> Die historische Access-Maske enthielt keine bestätigte Speicherlogik. Änderungen werden deshalb im Web nicht angeboten. Der in Access gespeicherte Filter <code>intIPbyte3 = 185</code> wird nicht erzwungen.</div>
<form class="search" method="get"><label>Kundennummer<input name="kunde" value="{{ $customer }}" inputmode="numeric"></label><label>IP-Adresse<input name="ip" value="{{ $ip }}" placeholder="z. B. 212.79.162"></label><button class="button">Suchen</button><a class="button" href="{{ route('ipv4-reverse.index') }}">Filter löschen</a></form>
<table class="tbl"><thead><tr><th>ID</th><th>IPv4-Adresse</th><th>Kundennummer</th></tr></thead><tbody>@forelse($rows as $r)<tr><td>{{ $r->intID }}</td><td>{{ $r->intIPbyte1 }}.{{ $r->intIPbyte2 }}.{{ $r->intIPbyte3 }}.{{ $r->intIPbyte4 }}</td><td>{{ $r->intKundenID }}</td></tr>@empty<tr><td colspan="3">Keine Einträge gefunden.</td></tr>@endforelse</tbody></table>
<div class="pager">{{ $rows->links() }}</div><p><a class="button" href="{{ route('dashboard') }}" data-db-inline="1">Schliessen</a></p>
</div><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>
