<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $titles[$variant] }}</title><style>
*{box-sizing:border-box}body{font:13px Arial;background:#d9d9d9;margin:0;padding:12px;color:#111}.window{max-width:1180px;margin:auto;background:#efefef;border:1px solid #888;padding:14px}.top{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.filters{display:flex;gap:10px;flex-wrap:wrap;align-items:end;margin:12px 0}.filters label{display:block;font-size:11px;margin-bottom:3px}.filters input,.filters select{padding:6px;border:1px solid #999}.button{display:inline-block;padding:7px 11px;border:1px solid #777;background:#eee;color:#111;text-decoration:none;cursor:pointer}.summary{background:#fff;border:1px solid #aaa;padding:9px;margin:10px 0}.customer{margin:12px 0;padding:10px;background:#fff;border:1px solid #aaa}table{width:100%;border-collapse:collapse;background:#fff}th,td{border:1px solid #aaa;padding:6px;vertical-align:top}th{background:#e3e3e3;text-align:left}.num{text-align:right;white-space:nowrap}.extra{font-size:12px;color:#333;margin-top:4px}.total td{font-weight:bold;background:#eee}.empty{padding:16px;background:#fff;border:1px solid #aaa}.nav{margin-top:12px}
</style></head><body><div class="window"><div class="top"><div><h2 style="margin:0">{{ $titles[$variant] }}</h2></div><a href="{{ route('frontend.switch','modern') }}">Zum neuen Frontend wechseln →</a></div>
<form class="filters" method="get"><input type="hidden" name="variante" value="{{ $variant }}"><div><label>Kundennummer</label><input type="number" min="1" name="kunde" value="{{ $kundenId }}" required></div><div><label>Monat</label><input type="number" min="1" max="12" name="monat" value="{{ $monat }}" required></div><div><label>Jahr</label><input type="number" min="1990" max="2100" name="jahr" value="{{ $jahr }}" required></div><button class="button">Anzeigen</button></form>
@if($kunde)<div class="customer"><strong>{{ $kunde->strAnrede }} {{ $kunde->strName }}</strong><br>{{ $kunde->strStrasse }}<br>{{ $kunde->strPLZ }} {{ $kunde->strOrt }}<br>Kundennummer: {{ $kunde->intID }}</div>@elseif($kundenId)<div class="empty">Kunde {{ $kundenId }} wurde nicht gefunden.</div>@endif
@if($kundenId && $kunde)<div class="summary">Zeitraum: {{ str_pad($monat,2,'0',STR_PAD_LEFT) }}/{{ $jahr }} · Datensätze: {{ $rows->count() }}</div>
@if($rows->isEmpty())<div class="empty">Keine Accounting-Daten für diese Auswahl.</div>@else<table><thead><tr><th>Anbindung</th><th>Typ</th><th>Rechnungsinfo</th><th class="num">MB In</th><th class="num">MB Out</th><th class="num">Gesamt MB</th></tr></thead><tbody>
@foreach($rows as $r)<tr><td>{{ $r->intAnbID }}</td><td>{{ $r->intTyp }}</td><td>{{ $r->strrechnungsinfo }}@if($variant !== 'ohne-zusatzinfos' && $r->zusatzinfo)<div class="extra">{{ $r->zusatzinfo }}</div>@endif</td><td class="num">{{ number_format((float)$r->decMBin,2,',','.') }}</td><td class="num">{{ number_format((float)$r->decMBout,2,',','.') }}</td><td class="num">{{ number_format((float)$r->decGesamt,2,',','.') }}</td></tr>@endforeach
@if($variant !== 'ohne-zusatzinfos')<tr class="total"><td colspan="3">Summe</td><td class="num">{{ number_format($totals['in'],2,',','.') }}</td><td class="num">{{ number_format($totals['out'],2,',','.') }}</td><td class="num">{{ number_format($totals['gesamt'],2,',','.') }}</td></tr>@endif
</tbody></table>@endif @endif
<div class="nav"><a class="button" href="{{ route('dashboard') }}">← Hauptmenü</a></div></div><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>
