<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Offene Rechnungen - {{ $kunde->strName }}</title>
<style>body{font:13px Arial;background:#d9d9d9;padding:12px}.window{max-width:1200px;margin:auto;background:#efefef;border:1px solid #888;padding:14px}.title{color:#0000cc;font-weight:bold;border-bottom:2px solid #0000cc;margin-bottom:12px}.button{display:inline-block;padding:7px 12px;border:1px solid #777;background:#eee;color:#111;text-decoration:none}table{width:100%;border-collapse:collapse;background:#fff}th,td{border:1px solid #aaa;padding:5px;vertical-align:top}th{background:#ddd}.money{text-align:right;white-space:nowrap}.muted{color:#666}.warn{color:#9a3412;font-weight:bold}</style></head><body><div class="window">
<h2>Offene Rechnungen</h2><div class="title">{{ $kunde->strName }} (#{{ $kunde->intID }})</div>
@if($rechnungen->isEmpty())<p>Keine offenen Rechnungen vorhanden.</p>@else
<table><thead><tr><th>Rechnung</th><th>Auftrag</th><th>Rechnungsdatum</th><th>Fällig</th><th>Kundenname auf Rechnung</th><th>Netto</th><th>Steuer</th><th>Rechnungsbetrag</th><th>Bezahlt</th><th>Mahnstufe</th><th>Hinweise</th></tr></thead><tbody>
@foreach($rechnungen as $r)<tr>
<td>{{ $r->intRechNr }}</td><td>{{ $r->intAufNr }}</td><td>{{ $r->datRechnungsDatum ? date('d.m.Y', strtotime($r->datRechnungsDatum)) : '' }}</td><td>{{ $r->datFaelligkeitsDatum ? date('d.m.Y', strtotime($r->datFaelligkeitsDatum)) : '' }}</td><td>{{ $r->strKundenNameAufRechnung }}</td>
<td class="money">{{ number_format((float)$r->fBetrag,2,',','.') }} €</td><td class="money">{{ number_format((float)$r->fSteuer,2,',','.') }} €</td><td class="money"><strong>{{ number_format((float)$r->fRechnungsbetrag,2,',','.') }} €</strong></td><td class="money">{{ number_format((float)$r->fBezahlterBetrag,2,',','.') }} €</td><td>{{ $r->intMahnstufe ?? '-' }}</td>
<td>@if($r->bolRechnungStrittig)<span class="warn">Strittig @if($r->strRechnungStrittigGrund) · {{ $r->strRechnungStrittigGrund }} @endif</span><br>@endif @if($r->datMahnung1Am)<span class="muted">1. Mahnung: {{ date('d.m.Y',strtotime($r->datMahnung1Am)) }}</span><br>@endif @if($r->datMahnung2Am)<span class="muted">2. Mahnung: {{ date('d.m.Y',strtotime($r->datMahnung2Am)) }}</span><br>@endif @if($r->datMahnung3Am)<span class="muted">3. Mahnung: {{ date('d.m.Y',strtotime($r->datMahnung3Am)) }}</span>@endif</td>
</tr>@endforeach</tbody></table>@endif
<p><a class="button" href="{{ route('kunden.show',$kunde->intID) }}">Zurück zum Kunden</a></p></div><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>