<!doctype html>
<html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Rechnungstool</title>
<style>
body{font-family:Tahoma,Arial,sans-serif;background:#d9d9d9;margin:0;padding:18px;color:#111}.window{max-width:1500px;margin:auto;background:#efefef;border:1px solid #777;box-shadow:0 1px 2px #0002}.titlebar{padding:10px 12px;font-weight:700;font-size:18px;background:#f5f5f5;border-bottom:1px solid #aaa}.tabs{display:flex;gap:2px;padding:8px 10px 0}.tab{border:1px solid #999;background:#e7e7e7;padding:6px 10px;cursor:pointer;font-size:13px}.tab.active{background:#fff;border-bottom-color:#fff}.panel{display:none;margin:0 10px 10px;border:1px solid #999;background:#fff;padding:16px;min-height:180px}.panel.active{display:block}.row{display:flex;gap:14px;align-items:center;flex-wrap:wrap;margin:8px 0}.row label{min-width:160px}.row input,.row select{font:inherit;padding:4px}.help{max-width:850px;line-height:1.35}.actions{display:flex;justify-content:space-between;align-items:center;padding:10px;border-top:1px solid #aaa;background:#f5f5f5}.btn{font:inherit;padding:7px 18px;border:1px solid #888;background:#eee;color:#111;text-decoration:none;cursor:pointer}.btn.primary{background:#e5e5e5}.btn[disabled]{color:#888;cursor:not-allowed}.notice{margin:12px 10px;background:#fff7d6;border:1px solid #c8b24d;padding:10px}.table-wrap{overflow:auto}.results{margin:12px 10px;border:1px solid #999;background:#fff}.results h2,.preview h2{margin:0;padding:10px;background:#eee;border-bottom:1px solid #aaa;font-size:16px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid #bbb;padding:6px 7px;vertical-align:top;text-align:left}th{background:#ececec;white-space:nowrap}.selected-row{background:#fff4c7}.preview{margin:12px 10px;border:1px solid #999;background:#fff}.preview-body{padding:10px}.muted{color:#666}.warning{background:#fff4c7;border:1px solid #c99;padding:8px}.small{font-size:12px}.back{color:#333}.quick button{margin-right:8px}
</style></head>
<body>
<x-page-help title="Rechnungstool">Hier werden Aufträge für die Fakturierung geprüft, Dokumente vorbereitet und E-Rechnungen validiert. Vorschauen sind lesend. Produktive Rechnungserzeugung ist zusätzlich durch Berechtigung, Serverfreigabe und Bestätigungsphrase geschützt.</x-page-help>
<div class="window"><div class="titlebar">Rechnungen schreiben: Rechnungstool</div>
<div class="notice"><strong>Phase 1: rein lesender Testlauf.</strong> Keine Rechnungserzeugung und keine abrechnungsrelevanten Schreibvorgänge.</div>
<form method="get" action="{{ route('fakturierung.index') }}" id="classicForm">
<div class="tabs">
<button type="button" class="tab active" data-tab="datum">Datumsbereich</button><button type="button" class="tab" data-tab="test">Test/Monatslauf</button><button type="button" class="tab" data-tab="auftrag">Auftrags/Kundennummer</button><button type="button" class="tab" data-tab="logging">Logging</button>
</div>
<div class="panel active" id="tab-datum"><div class="help">Du kannst verschiedene Daten, die mit der Rechnungslegung zu tun haben, frei anpassen. Alle Auftragspositionen zwischen Beginn und Ende des Rechnungslaufs werden berücksichtigt.</div>
<div class="row"><label>Beginn des Rechnungslaufs:</label><input type="date" name="von" value="{{ $von }}"></div><div class="row"><label>Ende des Rechnungslaufs:</label><input type="date" name="bis" value="{{ $bis }}"></div><div class="row"><label>Datum des Rechnungslaufs:</label><input type="date" name="rechnungsdatum" value="{{ $rechnungsdatum }}"></div>
<div class="row quick"><button type="button" class="btn" data-range="current">Aktueller Monat</button><button type="button" class="btn" data-range="today">Heute</button><button type="button" class="btn" data-range="last">Letzter Monat</button></div></div>
<div class="panel" id="tab-test"><div class="row"><label><input type="checkbox" checked disabled> Testlauf</label></div><div class="help">Der Weblauf bleibt in Phase 1 zwingend ein Testlauf. Rechnungen und Abrechnungsdaten werden nicht verändert.</div><div class="row"><label><input type="checkbox" name="accountings" value="1" @checked($accountings)> Accountings berücksichtigen</label><span class="muted">Staffeln, Linearstaffeln, Zeittarife, Bandbreiten, Domainpreise und Bereichsstaffeln werden im Testlauf bereits lesend ausgewertet.</span></div><div class="row"><label><input type="checkbox" disabled> Dokument erzeugen</label><span class="muted">ersetzt später die alte Word-Ausgabe</span></div><div class="row"><label><input type="checkbox" disabled> Auftragsbestätigung generieren</label></div></div>
<div class="panel" id="tab-auftrag"><div class="help">Wie im bisherigen Tool können Auftrag oder Kunde gezielt eingeschränkt werden. 0 bedeutet alle.</div><div class="row"><label>Auftragsnummer (0 für alle):</label><input type="number" min="0" name="auftragsnr" value="{{ $auftragsnr }}"></div><div class="row"><label>Kundennummer (0 für alle):</label><input type="number" min="0" name="kundennr" value="{{ $kundennr }}"></div><div class="row"><label>Abrechnungsart:</label><select name="art"><option value="nachtraeglich" @selected($art==='nachtraeglich')>Nachträglich abrechnen</option><option value="voraus" @selected($art==='voraus')>Im Voraus abrechnen</option><option value="domain" @selected($art==='domain')>Domainaufträge</option></select></div><div class="row"><label>Zusätzliche Suche:</label><input type="text" name="q" value="{{ $q }}" placeholder="Beschreibung / Rechnungsanschrift" size="36"></div><div class="row"><label><input type="checkbox" disabled> Nur Einzüge ohne Papierrechnung bearbeiten</label><span class="muted">folgt mit der vollständigen Laufsteuerung</span></div></div>
<div class="panel" id="tab-logging"><div class="help">Das Web-Rechnungstool wird das Protokoll direkt im System führen. Ein lokaler Dateipfad wie im alten Tool ist nicht mehr erforderlich.</div><div class="row"><label>Aktueller Benutzer:</label><strong>{{ $adUsername ?: 'unbekannt' }}</strong></div><div class="row"><label>Protokollstatus:</label><span class="muted">lesende Einzel-, Kunden- und Gesamttestläufe aktiv</span></div></div>
<div class="actions"><div><a class="back" href="{{ route('dashboard') }}">← Hauptmenü</a> · <a class="back" href="{{ route('frontend.switch', 'modern') }}">Moderne Ansicht</a> · <a class="back" href="{{ route('mahnwesen.index') }}">Mahnwesen</a></div><div><button class="btn" type="button" disabled title="Die Auftragsliste wird im Classic-Modus später wieder als eigene Ansicht umgesetzt.">Auftragsliste</button> <button class="btn primary" type="submit" name="lauf" value="auto" title="Mit Auftrag/Kunde eingeschränkt oder bei 0/0 als Gesamttestlauf starten">Start</button></div></div></form>
</div>
@if($batchRunError)<div class="results"><h2>Testlauf nicht gestartet</h2><div class="preview-body warning">{{ $batchRunError }}</div></div>@endif
@if($batchTestRun)<div class="results"><h2>{{ $batchTestRun['scopeLabel'] }} · {{ $batchTestRun['orderCount'] }} Aufträge</h2><div class="preview-body"><div class="row"><strong>Fakturierbar:</strong> {{ $batchTestRun['readyCount'] }} · <strong>Nichts neu:</strong> {{ $batchTestRun['nothingCount'] }} · <strong>Blockiert:</strong> {{ $batchTestRun['blockedCount'] }} · <strong>Brutto fakturierbar:</strong> {{ number_format($batchTestRun['gross'],2,',','.') }} €</div><div class="table-wrap"><table><thead><tr><th>Auftrag</th><th>Kunde</th><th>Status</th><th>Netto</th><th>Brutto</th><th>Hinweis/Fehler</th></tr></thead><tbody>@foreach($batchTestRun['rows'] as $batchRow)<tr><td>#{{ $batchRow->order->intAufNr }}<br><span class="muted">{{ $batchRow->order->strBeschreibung }}</span></td><td>{{ $batchRow->customerName }}</td><td>{{ $batchRow->statusLabel }}</td><td>{{ $batchRow->status === 'ready' ? number_format($batchRow->net,2,',','.').' €' : '–' }}</td><td>{{ $batchRow->status === 'ready' ? number_format($batchRow->gross,2,',','.').' €' : '–' }}</td><td>@foreach($batchRow->issues as $issue)<div>{{ $issue }}</div>@endforeach @foreach($batchRow->warnings as $warning)<div class="muted">{{ $warning }}</div>@endforeach</td></tr>@endforeach</tbody></table></div></div></div>@endif
<script>
const tabs=document.querySelectorAll('.tab'), panels=document.querySelectorAll('.panel');tabs.forEach(t=>t.addEventListener('click',()=>{tabs.forEach(x=>x.classList.remove('active'));panels.forEach(x=>x.classList.remove('active'));t.classList.add('active');document.getElementById('tab-'+t.dataset.tab).classList.add('active')}));
function iso(d){return d.toISOString().slice(0,10)};document.querySelectorAll('[data-range]').forEach(b=>b.addEventListener('click',()=>{let n=new Date(),v,e;if(b.dataset.range==='current'){v=new Date(n.getFullYear(),n.getMonth(),1);e=new Date(n.getFullYear(),n.getMonth()+1,0)}else if(b.dataset.range==='today'){v=new Date(n.getFullYear(),n.getMonth(),1);e=n}else{v=new Date(n.getFullYear(),n.getMonth()-1,1);e=new Date(n.getFullYear(),n.getMonth(),0)}document.querySelector('[name=von]').value=iso(v);document.querySelector('[name=bis]').value=iso(e)}));
</script>
<div class="results" style="margin-top:16px;border:1px solid #6c83a8"><h2>Rechnungsnummern-Simulation</h2><div class="preview-body">
<div class="row"><strong>Nummernkreis:</strong> {{ $invoiceNumberSimulation['year'] }} · <strong>Letzte vorhandene Nummer:</strong> {{ $invoiceNumberSimulation['current'] ? number_format($invoiceNumberSimulation['current'],0,'','') : 'keine' }} · <strong>Simulierte nächste Nummer:</strong> {{ number_format($invoiceNumberSimulation['next'],0,'','') }} · <strong>Vorhandene Rechnungen:</strong> {{ $invoiceNumberSimulation['invoiceCount'] }}</div>
<div class="warning"><strong>Nur Vorschau:</strong> Die Nummer wird weder vergeben noch reserviert. Ein paralleler Lauf des Alttools kann sie zuerst verwenden.</div>
@foreach($invoiceNumberSimulation['warnings'] as $warning)<div class="warning">{{ $warning }}</div>@endforeach
</div></div>
<div class="results" style="margin-top:16px;border:1px solid #6c83a8"><h2>Produktive Schreiblogik</h2><div class="preview-body">
@if(session('status'))<div class="row">{{ session('status') }}</div>@endif
@if($errors->has('rechnung'))<div class="warning">{{ $errors->first('rechnung') }}</div>@endif
<div class="{{ $invoiceWriteReadiness['permissionsComplete'] ? 'row' : 'warning' }}"><strong>SQL-Schreibrechte:</strong> {{ $invoiceWriteReadiness['permissionsComplete'] ? 'vollständig' : 'noch nicht vollständig' }} · <strong>PDF-Ablage:</strong> {{ $invoiceWriteReadiness['storageReady'] ? 'bereit' : 'nicht bereit' }} · <strong>Serverfreigabe:</strong> {{ $invoiceWriteReadiness['enabled'] ? 'aktiv' : 'deaktiviert' }}.</div>
@if($invoiceWriteReadiness['enabled'] && $invoiceWriteReadiness['permissionsComplete'] && $invoiceWriteReadiness['storageReady'] && $selected && $orderTestRun && $orderTestRun['status']==='ready')
<form method="post" action="{{ route('fakturierung.commit') }}" class="row">@csrf
<input type="hidden" name="auftrag" value="{{ $selected->intAufNr }}"><input type="hidden" name="von" value="{{ $von }}"><input type="hidden" name="bis" value="{{ $bis }}"><input type="hidden" name="rechnungsdatum" value="{{ $rechnungsdatum }}"><input type="hidden" name="accountings" value="{{ $accountings ? '1' : '0' }}">
<label>Exakt eingeben: <strong>{{ config('invoicing.confirmation_phrase') }}</strong> <input name="bestaetigung" autocomplete="off"></label>
@error('bestaetigung')<div class="warning">{{ $message }}</div>@enderror
<button class="btn primary" type="submit">Rechnung verbindlich erzeugen</button></form>
@else
<div class="small muted">Schreiben ist weiterhin gesperrt. Vorschau und PDF bleiben rein lesend.</div>
@endif
</div></div>
<div class="results" style="margin-top:16px;border:1px solid #6c83a8"><h2>Historischer Paritätsvergleich</h2><div class="preview-body">
<form method="get" class="row"><label>Rechnungsnummer oder interne Rechnungs-ID:</label><input type="number" min="1" name="vergleich" value="{{ $parityIdentifier ?: '' }}" required><button class="btn primary">Rechnung vergleichen</button></form>
<div class="small muted">Rein lesende Neuberechnung anhand der historisch gespeicherten Berechnungstermine.</div>
@if($parityComparison)
@if(isset($parityComparison['error']))<div class="warning">{{ $parityComparison['error'] }}</div>
@else
<div class="row"><strong>Rechnung {{ $parityComparison['invoice']->intRechNr }}</strong> · Auftrag #{{ $parityComparison['invoice']->intAufNr }} · {{ $parityComparison['from']->format('d.m.Y') }}–{{ $parityComparison['to']->format('d.m.Y') }} · <strong>{{ $parityComparison['matches'] ? 'Übereinstimmung' : 'Abweichung' }}</strong></div>
<div class="table-wrap"><table><thead><tr><th>Wert</th><th>Historisch</th><th>Web-Neuberechnung</th><th>Differenz</th></tr></thead><tbody>
@foreach(['Netto'=>'Net','Steuer'=>'Tax','Brutto'=>'Gross'] as $label=>$key)<tr><td>{{ $label }}</td><td>{{ number_format($parityComparison['stored'.$key],2,',','.') }} €</td><td>{{ number_format($parityComparison['replayed'.$key],2,',','.') }} €</td><td @if(abs($parityComparison[strtolower($key).'Difference'])>=0.01) class="warning" @endif>{{ number_format($parityComparison[strtolower($key).'Difference'],2,',','.') }} €</td></tr>@endforeach
</tbody></table></div>
<div class="table-wrap"><table><thead><tr><th>Termin / Position</th><th>Rabatt</th><th>Netto historisch</th><th>Netto Web</th><th>Steuer historisch</th><th>Steuer Web</th><th>Status</th></tr></thead><tbody>
@foreach($parityComparison['rows'] as $row)<tr @if(!$row->matches) class="warning" @endif><td>{{ \Carbon\Carbon::parse($row->stored->BerechnetZum)->format('d.m.Y') }} · #{{ $row->stored->intAufPosID }}<br><span class="muted">{{ $row->stored->strKopieBeschreibung ?: $row->stored->strBeschreibung }}</span></td><td>{{ number_format($row->discountPercent,2,',','.') }} %<br>{{ number_format($row->storedDiscount,2,',','.') }} €</td><td>{{ number_format($row->storedNet,2,',','.') }} €</td><td>{{ $row->replayed ? number_format($row->replayed->net,2,',','.').' €' : 'fehlt' }}</td><td>{{ number_format($row->storedTax,2,',','.') }} €</td><td>{{ $row->replayed ? number_format($row->replayed->tax,2,',','.').' €' : 'fehlt' }}</td><td>{{ $row->matches ? 'OK' : 'Abweichung' }}</td></tr>@endforeach
</tbody></table></div>
@if($parityComparison['unexpectedRows']->isNotEmpty())<div class="warning"><strong>Zusätzliche Web-Zeilen:</strong> {{ $parityComparison['unexpectedRows']->count() }} neu berechnete Position(en) gehören nicht zu den gespeicherten Zeilen dieser Rechnung.</div>@endif
@endif
@endif
</div></div>
<div class="results" style="margin-top:16px;border:1px solid #c9a84c"><h2>Tägliche Konsistenzprüfung · {{ $manualReviewIssues->count() }} Punkte</h2><div class="preview-body"><div class="row"><strong>Automatische rein lesende Prüfung täglich um 08:00 Uhr.</strong> @if($manualReviewReport['generated_at']) Letzte Prüfung: {{ \Carbon\Carbon::parse($manualReviewReport['generated_at'])->timezone('Europe/Berlin')->format('d.m.Y H:i') }} Uhr · geprüfter Abrechnungszeitraum {{ \Carbon\Carbon::parse($manualReviewReport['period_from'])->format('d.m.Y') }}–{{ \Carbon\Carbon::parse($manualReviewReport['period_to'])->format('d.m.Y') }}. @else Noch kein Prüfbericht vorhanden. @endif</div>@if($manualReviewIssues->isEmpty())<div class="row"><strong>Keine aktuellen Auffälligkeiten gefunden.</strong></div>@else<div class="table-wrap"><table><thead><tr><th>Auftrag</th><th>Kunde</th><th>Kategorie</th><th>Prüfhinweis</th></tr></thead><tbody>@foreach($manualReviewIssues as $problem)<tr><td>@if($problem['order'] > 0)<a href="{{ route('fakturierung.index',array_filter(['von'=>$von,'bis'=>$bis,'art'=>$art,'accountings'=>$accountings?'1':null,'rechnungsdatum'=>$rechnungsdatum,'auftrag'=>$problem['order'],'ansicht'=>'modern'])) }}" data-window-title="Auftrag #{{ $problem['order'] }} · Rechnungsvorschau">#{{ $problem['order'] }}</a>@else System @endif</td><td>{{ $problem['customer'] }}</td><td>{{ $problem['category'] }}</td><td>{{ $problem['issue'] }}</td></tr>@endforeach</tbody></table></div>@endif</div></div>
</body></html>
