<!DOCTYPE html>
<html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lastschriften bezahlt markieren</title>
<style>*{box-sizing:border-box}body{margin:0;font:14px Segoe UI,Arial;background:#f4f6f8;color:#1f2937}.page{max-width:1280px;margin:auto;padding:28px}.card{background:#fff;border-radius:12px;box-shadow:0 2px 8px #0001;padding:22px}.top{display:flex;justify-content:space-between;gap:16px;align-items:center}.filter{display:flex;gap:12px;align-items:end;flex-wrap:wrap;margin:16px 0}.field label{display:block;margin-bottom:5px;font-size:12px;text-transform:uppercase;color:#64748b}.field input{padding:9px;border:1px solid #cbd5e1;border-radius:6px}.button{display:inline-block;padding:9px 14px;border:0;border-radius:7px;background:#0069c2;color:#fff;text-decoration:none;cursor:pointer}.button.danger{background:#b42318}.summary{padding:12px;border-radius:8px;background:#f8fafc;margin:12px 0}.ok{padding:11px;border-radius:8px;background:#dcfce7;margin:10px 0}.err{padding:11px;border-radius:8px;background:#fee2e2;margin:10px 0}.table-wrap{overflow:auto;border:1px solid #e2e8f0;border-radius:8px}table{width:100%;border-collapse:collapse;white-space:nowrap}th,td{padding:9px 10px;border-bottom:1px solid #e2e8f0;text-align:left}th{background:#f8fafc;position:sticky;top:0}.num{text-align:right}.confirm{margin:14px 0;padding:13px;border-radius:8px;background:#fff7ed;border:1px solid #fed7aa}.muted{color:#94a3b8}</style></head>
<body><div class="page"><div class="card"><div class="top"><h1>Lastschriften bezahlt markieren</h1><a href="{{ route('frontend.switch','classic') }}">← Zur klassischen Ansicht</a></div>
@if(session('success'))<div class="ok">{{ session('success') }}</div>@endif @if($errors->any())<div class="err">{{ $errors->first() }}</div>@endif
<form method="get" action="{{ route('lastschriften.index') }}" class="filter"><div class="field"><label>Fällig ab</label><input type="date" name="von" value="{{ $von }}" required></div><div class="field"><label>Fällig bis</label><input type="date" name="bis" value="{{ $bis }}" required></div><button class="button" type="submit">Anzeigen</button></form>
<div class="summary"><strong>{{ $rows->count() }}</strong> offene Lastschrift(en) · Zu buchende Gesamtsumme: <strong>{{ number_format($summe,2,',','.') }} €</strong></div>
<div class="table-wrap"><table><thead><tr><th>ID</th><th>Rechnung</th><th>Auftrag</th><th>Kunde</th><th>Fälligkeit</th><th>Zahlungsbed.</th><th class="num">Rechnungsbetrag</th><th class="num">Zahlbetrag</th></tr></thead><tbody>
@forelse($rows as $r)<tr><td>{{ $r->intID }}</td><td>@if($r->intRechNr)<a href="{{ route('rechnungen.show',$r->intID) }}">{{ $r->intRechNr }}</a>@else<span class="muted">–</span>@endif</td><td>{{ $r->intAufNr }}</td><td>{{ $r->strKundenNameAufRechnung ?: '–' }}</td><td>{{ \Carbon\Carbon::parse($r->datFaelligkeitsDatum)->format('d.m.Y') }}</td><td>{{ $r->intZahlungsbedingungID }}</td><td class="num">{{ number_format((float)$r->fRechnungsbetrag,2,',','.') }} €</td><td class="num"><strong>{{ number_format((float)$r->zahlbetrag,2,',','.') }} €</strong></td></tr>@empty<tr><td colspan="8">Keine offenen Lastschriften im gewählten Zeitraum.</td></tr>@endforelse
</tbody></table></div>
@if($rows->isNotEmpty())<form method="post" action="{{ route('lastschriften.mark-paid') }}" onsubmit="return confirm('Sollen wirklich alle angezeigten Lastschriften als bezahlt markiert werden?');">@csrf<input type="hidden" name="von" value="{{ $von }}"><input type="hidden" name="bis" value="{{ $bis }}"><input type="hidden" name="confirm" value="1"><div class="confirm">Das Bezahldatum wird auf die jeweilige Fälligkeit gesetzt. Skonto 1, 2 und 3 werden in dieser Reihenfolge geprüft; die zuletzt gültige Stufe bestimmt den Zahlbetrag.</div><button class="button danger" type="submit">Alle angezeigten als bezahlt markieren</button></form>@endif
<p><a href="{{ route('dashboard') }}">← Hauptmenü</a></p></div></div><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>
