[global]
   workgroup = WORKGROUP
   server role = standalone server
   map to guest = Never
   security = user
   server min protocol = SMB2
   disable netbios = yes
   load printers = no
   printing = bsd
   printcap name = /dev/null
   log file = /dev/stdout
   max log size = 0

[Rechnungen]
   path = /share
   browseable = yes
   read only = no
   guest ok = no
   valid users = rechnungen
   force user = rechnungen
   create mask = 0666
   force create mode = 0666
   directory mask = 0777
   force directory mode = 0777
