[global]
   workgroup = WORKGROUP
   server role = standalone server
   map to guest = Bad User
   guest account = nobody
   security = user
   server min protocol = SMB2
   disable netbios = yes
   load printers = no
   printing = bsd
   printcap name = /dev/null
   log file = /dev/stdout
   max log size = 0

[Rechnungen]
   path = /share
   browseable = yes
   read only = no
   guest ok = yes
   guest only = yes
   force user = nobody
   create mask = 0666
   force create mode = 0666
   directory mask = 0777
   force directory mode = 0777
