<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $netz->intID ? 'Netz '.$netz->intID : 'Neues Netz' }}</title><style>
body{font:12px Tahoma,Arial;background:#d9d9d9;margin:0;padding:8px;color:#111}.window{width:620px;max-width:calc(100vw - 20px);margin:auto;background:#f0f0f0;border:1px solid #777;padding:8px}.title{font-weight:bold;font-size:14px;margin:2px 0 8px}.main{display:grid;grid-template-columns:1fr 100px;gap:10px}.left{min-width:0}.right{display:flex;flex-direction:column;gap:8px;padding-top:50px}.right .button{text-align:center}.line{display:grid;grid-template-columns:125px 1fr;gap:8px;align-items:center;margin:6px 0}.section{color:#0000cc;font-weight:bold;border-bottom:3px solid #0000cc;padding-bottom:3px;margin:7px 0 10px}.button{display:inline-block;padding:6px 10px;border:1px solid #777;background:#efefef;color:#111;text-decoration:none;box-shadow:inset 1px 1px #fff;cursor:pointer}input,textarea{box-sizing:border-box;width:100%;font:12px Tahoma,Arial;border:1px solid #888;background:#fff;padding:3px}textarea{min-height:78px;resize:vertical}.idbox{background:#d7d7d7;text-align:right;padding:4px 6px;border:1px solid #888}.check{width:auto}.nav{display:flex;align-items:center;gap:4px;margin-top:8px;border-top:1px solid #aaa;padding-top:5px}.nav a,.nav span{border:1px solid #aaa;background:#eee;padding:2px 5px;text-decoration:none;color:#111}.nav .plain{border:0;background:transparent}.ok,.err{padding:6px;margin-bottom:6px;border:1px solid}.ok{background:#e8f6e8;border-color:#4b8b4b}.err{background:#fee;border-color:#b91c1c}.search{margin-left:auto;display:flex;gap:4px}.search input{width:150px}
</style></head><body>
<x-page-help title="Netze pflegen">Hier werden IP-Netze gepflegt und technischen Zuordnungen zugewiesen. Änderungen wirken auf Netz- und gegebenenfalls Accountingdaten. Netzadresse und Präfix vor dem Speichern prüfen.</x-page-help>
<div class="window"><div style="display:flex;justify-content:space-between;align-items:center"><div class="title">Netze</div><a href="{{ route('frontend.switch','modern') }}">Zum neuen Frontend wechseln →</a></div>
@if(session('status'))<div class="ok">{{ session('status') }}</div>@endif @if($errors->any())<div class="err">{{ implode(' · ',$errors->all()) }}</div>@endif
<form method="post" action="{{ $netz->intID ? route('netze.update',$netz->intID) : route('netze.store') }}">@csrf @if($netz->intID)@method('PUT')@endif
<div class="main"><div class="left"><div class="line"><b>Netz-ID:</b><div class="idbox">{{ $netz->intID ?? '(neu)' }}</div></div><div class="section">Informationen über das jeweilige Netz:</div>
<div class="line"><span>Netzwerk:</span><input name="strNetzwerk" value="{{ old('strNetzwerk',$netz->strNetzwerk) }}" required autofocus></div>
<div class="line"><span>Netzmaske:</span><input type="number" min="0" max="32" name="intNetzmaske" value="{{ old('intNetzmaske',$netz->intNetzmaske) }}" required></div>
<div class="line"><span>GatewayRouter:</span><input type="number" name="intGatewayRouter" value="{{ old('intGatewayRouter',$netz->intGatewayRouter) }}"></div>
<div class="line"><span>KundenNetz:</span><label><input class="check" type="checkbox" name="intKundenNetz" value="1" @checked(old('intKundenNetz',(int)$netz->intKundenNetz)!==0)></label></div>
<div class="line"><span>AccountingEingerichtet:</span><label><input class="check" type="checkbox" name="intAccountingEingerichtet" value="1" @checked(old('intAccountingEingerichtet',(int)$netz->intAccountingEingerichtet)!==0)></label></div>
<div class="line"><span>InUse:</span><label><input class="check" type="checkbox" name="intInUse" value="1" @checked(old('intInUse',(int)$netz->intInUse)!==0)></label></div>
<div class="line"><span>Verwendung:</span><input name="strVerwendung" value="{{ old('strVerwendung',$netz->strVerwendung) }}"></div>
<div class="line"><span>Bemerkung:</span><input name="strBemerkung" value="{{ old('strBemerkung',$netz->strBemerkung) }}"></div>
<div class="line"><span>Standort:</span><input name="strStandort" maxlength="50" value="{{ old('strStandort',$netz->strStandort) }}"></div>
<div class="line"><span>Rechnungsinfo:</span><textarea name="strrechnungsinfo" required>{{ old('strrechnungsinfo',$netz->strrechnungsinfo) }}</textarea></div></div>
<div class="right"><a class="button" href="{{ route('netze.create') }}">Neues Netz</a><a class="button" href="{{ route('dashboard') }}">Schliessen</a><button class="button" type="submit">Speichern</button></div></div></form>
@if($nav)<div class="nav"><span class="plain">Datensatz:</span><a data-db-inline="1" href="{{ route('netze.index',array_merge($nav['query'],['rid'=>$nav['first']])) }}">|◀</a>@if($nav['prev'])<a data-db-inline="1" href="{{ route('netze.index',array_merge($nav['query'],['rid'=>$nav['prev']])) }}">◀</a>@else<span>◀</span>@endif<span>{{ $nav['index'] }} von {{ $nav['total'] }}</span>@if($nav['next'])<a data-db-inline="1" href="{{ route('netze.index',array_merge($nav['query'],['rid'=>$nav['next']])) }}">▶</a>@else<span>▶</span>@endif<a data-db-inline="1" href="{{ route('netze.index',array_merge($nav['query'],['rid'=>$nav['last']])) }}">▶|</a><form class="search" method="get" action="{{ route('netze.index') }}"><input name="q" value="{{ $q }}" placeholder="Suchen"><button class="button">Suchen</button>@if($q!=='')<a class="button" href="{{ route('netze.index') }}">Ungefiltert</a>@endif</form></div>@endif
<script src="{{ asset('js/db-window-manager.js') }}"></script></div></body></html>
