<?php

use App\Http\Controllers\AccountingBerichtController;
use App\Http\Controllers\AnsprechpartnerController;
use App\Http\Controllers\AnbindungController;
use App\Http\Controllers\AuftragController;
use App\Http\Controllers\BrancheController;
use App\Http\Controllers\BranchenAuswertungController;
use App\Http\Controllers\BereichsstaffelController;
use App\Http\Controllers\BandbreitenTarifController;
use App\Http\Controllers\KundeController;
use App\Http\Controllers\Ipv4ReverseController;
use App\Http\Controllers\NetzController;
use App\Http\Controllers\LastschriftController;
use App\Http\Controllers\LinearstaffelController;
use App\Http\Controllers\DocumentationController;
use App\Http\Controllers\DatevController;
use App\Http\Controllers\DialinController;
use App\Http\Controllers\DomainkonditionController;
use App\Http\Controllers\DomainEintragController;
use App\Http\Controllers\DomainCreateController;
use App\Http\Controllers\DomainOrderAssignmentController;
use App\Http\Controllers\DomainCustomerAssignmentController;
use App\Http\Controllers\FremdaccountingController;
use App\Http\Controllers\FakturierungController;
use App\Http\Controllers\OffeneRechnungenController;
use App\Http\Controllers\ProduktController;
use App\Http\Controllers\PortController;
use App\Http\Controllers\RechnungsanschriftController;
use App\Http\Controllers\RechnungController;
use App\Http\Controllers\RechnungslaufController;
use App\Http\Controllers\RechnungenOhneSteuerController;
use App\Http\Controllers\StaffelgruppeController;
use App\Http\Controllers\SmsZugangController;
use App\Http\Controllers\WiedervorlageController;
use App\Http\Controllers\ZeittarifController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    $mode = session('frontend_mode', 'classic');
    return view($mode . '.dashboard');
})->name('dashboard');

Route::get('/accounting-berichte', [AccountingBerichtController::class, 'index'])->name('accounting-berichte.index');
Route::get('/bandbreitentarife', [BandbreitenTarifController::class, 'index'])->name('bandbreitentarife.index');
Route::get('/bandbreitentarife/neu', [BandbreitenTarifController::class, 'create'])->name('bandbreitentarife.create');
Route::post('/bandbreitentarife', [BandbreitenTarifController::class, 'store'])->name('bandbreitentarife.store');
Route::get('/bandbreitentarife/{bandbreitentarif}/edit', [BandbreitenTarifController::class, 'edit'])->name('bandbreitentarife.edit');
Route::put('/bandbreitentarife/{bandbreitentarif}', [BandbreitenTarifController::class, 'update'])->name('bandbreitentarife.update');
Route::post('/bandbreitentarife/{bandbreitentarif}/preise', [BandbreitenTarifController::class, 'storePreis'])->name('bandbreitentarife.preise.store');
Route::put('/bandbreitentarife/{bandbreitentarif}/preise/{preis}', [BandbreitenTarifController::class, 'updatePreis'])->name('bandbreitentarife.preise.update');
Route::get('/bereichsstaffeln', [BereichsstaffelController::class, 'index'])->name('bereichsstaffeln.index');
Route::get('/bereichsstaffeln/neu', [BereichsstaffelController::class, 'create'])->name('bereichsstaffeln.create');
Route::post('/bereichsstaffeln', [BereichsstaffelController::class, 'store'])->name('bereichsstaffeln.store');
Route::get('/bereichsstaffeln/{bereichsstaffel}/edit', [BereichsstaffelController::class, 'edit'])->name('bereichsstaffeln.edit');
Route::put('/bereichsstaffeln/{bereichsstaffel}', [BereichsstaffelController::class, 'update'])->name('bereichsstaffeln.update');
Route::post('/bereichsstaffeln/{bereichsstaffel}/preise', [BereichsstaffelController::class, 'storePreis'])->name('bereichsstaffeln.preise.store');
Route::put('/bereichsstaffeln/{bereichsstaffel}/preise/{preis}', [BereichsstaffelController::class, 'updatePreis'])->name('bereichsstaffeln.preise.update');
Route::get('/sms-zugaenge', [SmsZugangController::class, 'index'])->name('sms-zugaenge.index');
Route::get('/sms-zugaenge/neu', [SmsZugangController::class, 'create'])->name('sms-zugaenge.create');
Route::post('/sms-zugaenge', [SmsZugangController::class, 'store'])->name('sms-zugaenge.store');
Route::get('/sms-zugaenge/{smsZugang}/edit', [SmsZugangController::class, 'edit'])->name('sms-zugaenge.edit');
Route::put('/sms-zugaenge/{smsZugang}', [SmsZugangController::class, 'update'])->name('sms-zugaenge.update');
Route::get('/staffelgruppen', [StaffelgruppeController::class, 'index'])->name('staffelgruppen.index');
Route::get('/staffelgruppen/neu', [StaffelgruppeController::class, 'create'])->name('staffelgruppen.create');
Route::post('/staffelgruppen', [StaffelgruppeController::class, 'store'])->name('staffelgruppen.store');
Route::get('/staffelgruppen/{staffelgruppe}/edit', [StaffelgruppeController::class, 'edit'])->name('staffelgruppen.edit');
Route::put('/staffelgruppen/{staffelgruppe}', [StaffelgruppeController::class, 'update'])->name('staffelgruppen.update');
Route::post('/staffelgruppen/{staffelgruppe}/preise', [StaffelgruppeController::class, 'storePreis'])->name('staffelgruppen.preise.store');
Route::put('/staffelgruppen/{staffelgruppe}/preise/{preis}', [StaffelgruppeController::class, 'updatePreis'])->name('staffelgruppen.preise.update');
Route::get('/staffelgruppen/{staffelgruppe}/rechner', [StaffelgruppeController::class, 'rechner'])->name('staffelgruppen.rechner');
Route::post('/staffelgruppen/{staffelgruppe}/rechner', [StaffelgruppeController::class, 'runRechner'])->name('staffelgruppen.rechner.run');
Route::get('/linearstaffeln', [LinearstaffelController::class, 'index'])->name('linearstaffeln.index');
Route::get('/linearstaffeln/neu', [LinearstaffelController::class, 'create'])->name('linearstaffeln.create');
Route::post('/linearstaffeln', [LinearstaffelController::class, 'store'])->name('linearstaffeln.store');
Route::get('/linearstaffeln/{linearstaffel}/edit', [LinearstaffelController::class, 'edit'])->name('linearstaffeln.edit');
Route::put('/linearstaffeln/{linearstaffel}', [LinearstaffelController::class, 'update'])->name('linearstaffeln.update');
Route::get('/zeittarife', [ZeittarifController::class, 'index'])->name('zeittarife.index');
Route::get('/zeittarife/neu', [ZeittarifController::class, 'create'])->name('zeittarife.create');
Route::post('/zeittarife', [ZeittarifController::class, 'store'])->name('zeittarife.store');
Route::get('/zeittarife/{zeittarif}/edit', [ZeittarifController::class, 'edit'])->name('zeittarife.edit');
Route::put('/zeittarife/{zeittarif}', [ZeittarifController::class, 'update'])->name('zeittarife.update');
Route::post('/zeittarife/{zeittarif}/zonen', [ZeittarifController::class, 'storeZone'])->name('zeittarife.zonen.store');
Route::put('/zeittarife/{zeittarif}/zonen/{zone}', [ZeittarifController::class, 'updateZone'])->name('zeittarife.zonen.update');
Route::get('/dialins', [DialinController::class, 'index'])->name('dialins.index');
Route::get('/dialins/neu', [DialinController::class, 'create'])->name('dialins.create');
Route::post('/dialins', [DialinController::class, 'store'])->name('dialins.store');
Route::get('/dialins/{dialin}/edit', [DialinController::class, 'edit'])->name('dialins.edit');
Route::put('/dialins/{dialin}', [DialinController::class, 'update'])->name('dialins.update');
Route::post('/dialins/{dialin}/einwahlnummern', [DialinController::class, 'storeNumber'])->name('dialins.numbers.store');
Route::put('/dialins/{dialin}/einwahlnummern/{nummer}', [DialinController::class, 'updateNumber'])->name('dialins.numbers.update');
Route::get('/ports', [PortController::class, 'index'])->name('ports.index');
Route::get('/ports/neu', [PortController::class, 'create'])->name('ports.create');
Route::post('/ports', [PortController::class, 'store'])->name('ports.store');
Route::get('/ports/{port}/edit', [PortController::class, 'edit'])->name('ports.edit');
Route::put('/ports/{port}', [PortController::class, 'update'])->name('ports.update');
Route::get('/netze', [NetzController::class, 'index'])->name('netze.index');
Route::get('/netze/neu', [NetzController::class, 'create'])->name('netze.create');
Route::post('/netze', [NetzController::class, 'store'])->name('netze.store');
Route::get('/netze/{netz}/edit', [NetzController::class, 'edit'])->name('netze.edit');
Route::put('/netze/{netz}', [NetzController::class, 'update'])->name('netze.update');
Route::get('/anbindungen', [AnbindungController::class, 'all'])->name('anbindungen.index');
Route::get('/anbindungen/neu', [AnbindungController::class, 'globalCreate'])->name('anbindungen.create');
Route::post('/anbindungen', [AnbindungController::class, 'globalStore'])->name('anbindungen.store');
Route::get('/anbindungen/{anbindung}/edit', [AnbindungController::class, 'globalEdit'])->name('anbindungen.edit');
Route::put('/anbindungen/{anbindung}', [AnbindungController::class, 'globalUpdate'])->name('anbindungen.update');
Route::get('/auftraege', [AuftragController::class, 'all'])->name('auftraege.index');
Route::get('/branchen-auswertung', [BranchenAuswertungController::class, 'index'])->name('branchen-auswertung.index');
Route::get('/branchen-auswertung/export', [BranchenAuswertungController::class, 'export'])->name('branchen-auswertung.export');
Route::get('/wiedervorlagen', [WiedervorlageController::class, 'index'])->name('wiedervorlagen.index');
Route::get('/fremdaccounting', [FremdaccountingController::class, 'index'])->name('fremdaccounting.index');
Route::get('/rechnungslauf', [RechnungslaufController::class, 'index'])->name('rechnungslauf.index');
Route::get('/rechnungslauf/export', [RechnungslaufController::class, 'export'])->name('rechnungslauf.export');
Route::get('/fakturierung', [FakturierungController::class, 'index'])->middleware('invoice.access')->name('fakturierung.index');
Route::get('/fakturierung/dokumentvorschau', [FakturierungController::class, 'documentPreview'])->middleware('invoice.access')->name('fakturierung.document-preview');
Route::get('/rechnungen-ohne-ust', [RechnungenOhneSteuerController::class, 'index'])->name('rechnungen-ohne-ust.index');
Route::get('/lastschriften', [LastschriftController::class, 'index'])->name('lastschriften.index');
Route::post('/lastschriften/bezahlt', [LastschriftController::class, 'markPaid'])->name('lastschriften.mark-paid');
Route::get('/produkte', [ProduktController::class, 'index'])->name('produkte.index');
Route::get('/produkte/neu', [ProduktController::class, 'create'])->name('produkte.create');
Route::post('/produkte', [ProduktController::class, 'store'])->name('produkte.store');
Route::get('/produkte/{produkt}/edit', [ProduktController::class, 'edit'])->name('produkte.edit');
Route::put('/produkte/{produkt}', [ProduktController::class, 'update'])->name('produkte.update');
Route::get('/rechnungen', [RechnungController::class, 'index'])->name('rechnungen.index');
Route::get('/rechnungen/{rechnung}', [RechnungController::class, 'show'])->name('rechnungen.show');
Route::get('/rechnungen/{rechnung}/datei', [RechnungController::class, 'file'])->name('rechnungen.file');
Route::get('/ipv4-reverse', [Ipv4ReverseController::class, 'index'])->name('ipv4-reverse.index');
Route::get('/domain-eintragen', [DomainCreateController::class, 'create'])->name('domain-create.create');
Route::post('/domain-eintragen', [DomainCreateController::class, 'store'])->name('domain-create.store');
Route::get('/domain-zu-auftragsposition', [DomainOrderAssignmentController::class, 'index'])->name('domain-order.index');
Route::post('/domain-zu-auftragsposition/zuordnen', [DomainOrderAssignmentController::class, 'assign'])->name('domain-order.assign');
Route::post('/domain-zu-auftragsposition/rabatte', [DomainOrderAssignmentController::class, 'saveDiscount'])->name('domain-order.discount');
Route::get('/domain-zu-kunden', [DomainCustomerAssignmentController::class, 'index'])->name('domain-customer.index');
Route::post('/domain-zu-kunden/zuordnen', [DomainCustomerAssignmentController::class, 'assign'])->name('domain-customer.assign');
Route::get('/domain-eintraege', [DomainEintragController::class, 'index'])->name('domain-eintraege.index');
Route::get('/domain-eintraege/{domain}', [DomainEintragController::class, 'show'])->name('domain-eintraege.show');
Route::post('/domain-eintraege/{domain}/eintraege', [DomainEintragController::class, 'store'])->name('domain-eintraege.store');
Route::put('/domain-eintraege/{domain}/eintraege/{entry}', [DomainEintragController::class, 'update'])->name('domain-eintraege.update');
Route::delete('/domain-eintraege/{domain}/eintraege/{entry}', [DomainEintragController::class, 'destroy'])->name('domain-eintraege.destroy');
Route::get('/domainkonditionen', [DomainkonditionController::class, 'index'])->name('domainkonditionen.index');
Route::get('/domainkonditionen/neu', [DomainkonditionController::class, 'create'])->name('domainkonditionen.create');
Route::post('/domainkonditionen', [DomainkonditionController::class, 'store'])->name('domainkonditionen.store');
Route::get('/domainkonditionen/{domainkondition}/edit', [DomainkonditionController::class, 'edit'])->name('domainkonditionen.edit');
Route::put('/domainkonditionen/{domainkondition}', [DomainkonditionController::class, 'update'])->name('domainkonditionen.update');
Route::get('/datev', [DatevController::class, 'index'])->name('datev.index');
Route::get('/datev/rechnungen', [DatevController::class, 'rechnungen'])->name('datev.rechnungen');
Route::get('/datev/produkte', [DatevController::class, 'produkte'])->name('datev.produkte');
Route::get('/datev/kunden', [DatevController::class, 'kunden'])->name('datev.kunden');
Route::get('/datev/kunden-ohne-datev', [DatevController::class, 'kundenOhneDatev'])->name('datev.kunden-ohne');
Route::get('/datev/kundenkonten', [DatevController::class, 'kundenkonten'])->name('datev.kundenkonten');
Route::get('/dokumentation', [DocumentationController::class, 'migration'])->name('documentation.migration');
Route::get('/handbuch', [DocumentationController::class, 'handbook'])->name('documentation.handbook');
Route::get('/rechnungstool-handbuch', [DocumentationController::class, 'invoiceHandbook'])->name('documentation.invoice-handbook');
Route::get('/sql-wiki', [DocumentationController::class, 'sqlWiki'])->name('documentation.sql-wiki');

Route::get('/kunden', [KundeController::class, 'index'])->name('kunden.index');
Route::get('/kunden/neu', [KundeController::class, 'create'])->name('kunden.create');
Route::post('/kunden', [KundeController::class, 'store'])->name('kunden.store');

Route::get('/kunden/{kunde}/ansprechpartner/neu', [AnsprechpartnerController::class, 'create'])->name('kunden.ansprechpartner.create');
Route::post('/kunden/{kunde}/ansprechpartner', [AnsprechpartnerController::class, 'store'])->name('kunden.ansprechpartner.store');
Route::get('/kunden/{kunde}/ansprechpartner/{ansprechpartner}/edit', [AnsprechpartnerController::class, 'edit'])->name('kunden.ansprechpartner.edit');
Route::put('/kunden/{kunde}/ansprechpartner/{ansprechpartner}', [AnsprechpartnerController::class, 'update'])->name('kunden.ansprechpartner.update');

Route::get('/kunden/{id}/branchen', [BrancheController::class, 'edit'])->name('kunden.branchen.edit');
Route::put('/kunden/{id}/branchen', [BrancheController::class, 'update'])->name('kunden.branchen.update');

Route::get('/kunden/{kunde}/rechnungsanschriften', [RechnungsanschriftController::class, 'index'])->name('kunden.rechnungsanschriften.index');
Route::get('/kunden/{kunde}/rechnungsanschriften/neu', [RechnungsanschriftController::class, 'create'])->name('kunden.rechnungsanschriften.create');
Route::post('/kunden/{kunde}/rechnungsanschriften', [RechnungsanschriftController::class, 'store'])->name('kunden.rechnungsanschriften.store');
Route::get('/kunden/{kunde}/rechnungsanschriften/{anschrift}/edit', [RechnungsanschriftController::class, 'edit'])->name('kunden.rechnungsanschriften.edit');
Route::put('/kunden/{kunde}/rechnungsanschriften/{anschrift}', [RechnungsanschriftController::class, 'update'])->name('kunden.rechnungsanschriften.update');

Route::get('/kunden/{kunde}/offene-rechnungen', [OffeneRechnungenController::class, 'index'])->name('kunden.offene-rechnungen.index');

Route::get('/kunden/{kunde}/auftraege', [AuftragController::class, 'index'])->name('kunden.auftraege.index');
Route::get('/kunden/{kunde}/auftraege/neu', [AuftragController::class, 'create'])->name('kunden.auftraege.create');
Route::post('/kunden/{kunde}/auftraege', [AuftragController::class, 'store'])->name('kunden.auftraege.store');
Route::get('/kunden/{kunde}/auftraege/{auftrag}/edit', [AuftragController::class, 'edit'])->name('kunden.auftraege.edit');
Route::put('/kunden/{kunde}/auftraege/{auftrag}', [AuftragController::class, 'update'])->name('kunden.auftraege.update');
Route::get('/kunden/{kunde}/auftraege/{auftrag}/positionen/neu', [AuftragController::class, 'createPosition'])->name('kunden.auftraege.positionen.create');
Route::post('/kunden/{kunde}/auftraege/{auftrag}/positionen', [AuftragController::class, 'storePosition'])->name('kunden.auftraege.positionen.store');
Route::get('/kunden/{kunde}/auftraege/{auftrag}/positionen/{position}/edit', [AuftragController::class, 'editPosition'])->name('kunden.auftraege.positionen.edit');
Route::put('/kunden/{kunde}/auftraege/{auftrag}/positionen/{position}', [AuftragController::class, 'updatePosition'])->name('kunden.auftraege.positionen.update');
Route::get('/kunden/{kunde}/auftraege/{auftrag}/positionen/{position}/anbindungen', [AnbindungController::class, 'index'])->name('kunden.auftraege.positionen.anbindungen.index');
Route::get('/kunden/{kunde}/auftraege/{auftrag}/positionen/{position}/anbindungen/neu', [AnbindungController::class, 'create'])->name('kunden.auftraege.positionen.anbindungen.create');
Route::post('/kunden/{kunde}/auftraege/{auftrag}/positionen/{position}/anbindungen', [AnbindungController::class, 'store'])->name('kunden.auftraege.positionen.anbindungen.store');
Route::get('/kunden/{kunde}/auftraege/{auftrag}/positionen/{position}/anbindungen/{anbindung}/edit', [AnbindungController::class, 'edit'])->name('kunden.auftraege.positionen.anbindungen.edit');
Route::put('/kunden/{kunde}/auftraege/{auftrag}/positionen/{position}/anbindungen/{anbindung}', [AnbindungController::class, 'update'])->name('kunden.auftraege.positionen.anbindungen.update');
Route::get('/kunden/{kunde}/auftraege/{auftrag}', [AuftragController::class, 'show'])->name('kunden.auftraege.show');

Route::get('/kunden/{id}/edit', [KundeController::class, 'edit'])->name('kunden.edit');
Route::put('/kunden/{id}', [KundeController::class, 'update'])->name('kunden.update');
Route::get('/kunden/{id}', [KundeController::class, 'show'])->name('kunden.show');

Route::get('/frontend/{mode}', function (Request $request, string $mode) {
    if (!in_array($mode, ['classic', 'modern'], true)) {
        abort(404);
    }
    session(['frontend_mode' => $mode]);
    return redirect()->back();
})->name('frontend.switch');
