<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $port->intid ? 'Port '.$port->intid : 'Neuer Port' }}</title><style>
body{font:12px Tahoma,Arial;background:#d9d9d9;margin:0;padding:8px}.window{width:830px;max-width:calc(100vw - 20px);margin:auto;background:#f0f0f0;border:1px solid #777;padding:8px}.title{font-weight:bold;font-size:14px}.main{display:grid;grid-template-columns:1fr 270px 105px;gap:10px}.line{display:grid;grid-template-columns:125px 1fr;gap:8px;align-items:center;margin:6px 0}.section{color:#0000cc;font-weight:bold;border-bottom:3px solid #0000cc;padding:4px 0}.button{display:inline-block;padding:6px 10px;border:1px solid #777;background:#efefef;color:#111;text-decoration:none;cursor:pointer}input,textarea{box-sizing:border-box;width:100%;font:12px Tahoma;border:1px solid #888;padding:3px}textarea{min-height:78px}.idbox,.ro{background:#d7d7d7;border:1px solid #888;padding:4px}.rightbox{border:1px solid #999;padding:8px}.rightbox h3{font-size:12px;margin:0 0 8px}.actions{display:flex;flex-direction:column;gap:8px}.warn{border:3px solid #111;background:#fff;padding:6px;font-weight:bold;margin-top:8px}.nav{display:flex;gap:4px;align-items:center;border-top:1px solid #aaa;margin-top:8px;padding-top:5px}.nav a,.nav span{border:1px solid #aaa;background:#eee;padding:2px 5px;text-decoration:none;color:#111}.nav .plain{border:0;background:transparent}.search{margin-left:auto;display:flex;gap:4px}.ok,.err{padding:6px;border:1px solid;margin-bottom:6px}.ok{background:#e8f6e8}.err{background:#fee}
</style></head><body>
<x-page-help title="Ports pflegen">Hier werden Ports und Port-Accounting-Zuordnungen gepflegt. Änderungen können die spätere Accounting-Auswertung und Abrechnung beeinflussen.</x-page-help>
<div class="window"><div style="display:flex;justify-content:space-between;align-items:center"><div class="title">Ports</div><a href="{{ route('frontend.switch','modern') }}">Zum neuen Frontend wechseln →</a></div>@if(session('status'))<div class="ok">{{session('status')}}</div>@endif @if($errors->any())<div class="err">{{implode(' · ',$errors->all())}}</div>@endif
<form method="post" action="{{ $port->intid ? route('ports.update',$port->intid) : route('ports.store') }}">@csrf @if($port->intid)@method('PUT')@endif
<div class="main"><div><div class="line"><b>Port-ID:</b><div class="idbox">{{$port->intid??'(neu)'}}</div></div><div class="section">Informationen über den jeweiligen Port:</div>
<div class="line"><span>RouterIP:</span><input name="strRouterIP" value="{{old('strRouterIP',$port->strRouterIP)}}" required autofocus></div>
<div class="line"><span>SNMPCommunity:</span><input name="strSNMPCommunity" value="{{old('strSNMPCommunity',$port->strSNMPCommunity)}}" @if(!$port->intid) list="community-list" @endif required></div>
<div class="line"><span>MIBVarIN:</span><input name="strMIBVarIN" value="{{old('strMIBVarIN',$port->strMIBVarIN)}}"></div><div class="line"><span>MIBVarOUT:</span><input name="strMIBVarOUT" value="{{old('strMIBVarOUT',$port->strMIBVarOUT)}}"></div>
<div class="line"><span>PortDescription:</span><input name="strPortDescription" value="{{old('strPortDescription',$port->strPortDescription)}}" @if(!$port->intid) list="description-list" @endif></div>
<div class="line"><span>Rechnungsinfo:</span><textarea name="strrechnungsinfo" required>{{old('strrechnungsinfo',$port->strrechnungsinfo)}}</textarea></div>
<div class="line"><span>OverrunLimit:</span><input name="decOverrunLimit" inputmode="numeric" value="{{old('decOverrunLimit',$port->decOverrunLimit)}}"></div>
<label><input style="width:auto" type="checkbox" name="boolDeaktiviert" value="1" @checked(old('boolDeaktiviert',(int)$port->boolDeaktiviert)!==0)> Accounting auf diesem Port deaktivieren (VORSICHT!)</label></div>
<div class="rightbox"><h3>PORTBESCHREIBUNG</h3><div>MIB zum Auslesen der ifDescr:</div><input name="strMIBVarDESCR" value="{{old('strMIBVarDESCR',$port->strMIBVarDESCR)}}"><div style="margin-top:7px">SOLL-Wert der ifDescr</div><input name="strIfDescrMust" value="{{old('strIfDescrMust',$port->strIfDescrMust)}}"><div style="margin-top:7px">IST-Wert der ifDescr</div><div class="ro">{{$port->strIfDescrCurrent}}</div><div style="margin-top:7px">Letztes Auslesen ifDescr</div><div class="ro">{{$port->dateIfDescrCurrent}}</div><div class="warn">Wenn IST und SOLL-Wert abweichen, muss auf dem Gerät die Port-Reihenfolge und Bezeichnung geprüft werden!</div></div>
<div class="actions"><a class="button" href="{{route('ports.create')}}">Neuer Port</a><a class="button" href="{{route('dashboard')}}">Schliessen</a><button class="button">Speichern</button></div></div>
<datalist id="description-list">@foreach($descriptionChoices as $x)<option value="{{$x}}">@endforeach</datalist><datalist id="community-list">@foreach($communityChoices as $x)<option value="{{$x}}">@endforeach</datalist></form>
@if($nav)<div class="nav"><span class="plain">Datensatz:</span><a data-db-inline="1" href="{{route('ports.index',array_merge($nav['query'],['rid'=>$nav['first']]))}}">|◀</a>@if($nav['prev'])<a data-db-inline="1" href="{{route('ports.index',array_merge($nav['query'],['rid'=>$nav['prev']]))}}">◀</a>@else<span>◀</span>@endif<span>{{$nav['index']}} von {{$nav['total']}}</span>@if($nav['next'])<a data-db-inline="1" href="{{route('ports.index',array_merge($nav['query'],['rid'=>$nav['next']]))}}">▶</a>@else<span>▶</span>@endif<a data-db-inline="1" href="{{route('ports.index',array_merge($nav['query'],['rid'=>$nav['last']]))}}">▶|</a><form class="search" method="get"><input name="q" value="{{$q}}" placeholder="Suchen"><button class="button">Suchen</button></form></div>@endif
<script src="{{asset('js/db-window-manager.js')}}"></script></div></body></html>
