<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><title>{{ $zeittarif ? 'Zeittarif '.$zeittarif->intID : 'Neuer Zeittarif' }}</title><style>
body{font:13px Arial;background:#f4f6f8;padding:12px;color:#111}.window{max-width:1050px;margin:auto;background:#fff;border:1px solid #d1d5db;border-radius:10px;box-shadow:0 2px 8px #0001;padding:14px}.top{display:flex;justify-content:space-between;align-items:center}.grid{display:grid;grid-template-columns:220px 1fr;gap:9px;align-items:center}input{width:100%;padding:6px;border:1px solid #999;background:#fff}.button{padding:7px 13px;border:1px solid #777;background:#eee;color:#111;text-decoration:none;cursor:pointer}.err{background:#fee;border:1px solid #b91c1c;padding:8px;margin-bottom:10px}.ok{background:#e8f6e8;border:1px solid #4b8b4b;padding:8px;margin-bottom:10px}.zones{margin-top:18px}table{width:100%;border-collapse:collapse;background:#fff}th,td{border:1px solid #aaa;padding:5px}th{background:#ddd}.inline{display:grid;grid-template-columns:80px 1fr 1fr 1fr auto;gap:5px;align-items:center}.inline input{min-width:0}.hint{font-size:12px;color:#666}
</style></head><body><div class="window"><div class="top"><h2>{{ $zeittarif ? 'Zeittarif '.$zeittarif->intID : 'Neuer Zeittarif' }}</h2><a href="{{ route('frontend.switch','classic') }}">← Zur klassischen Ansicht</a></div>
@if(session('status'))<div class="ok">{{ session('status') }}</div>@endif @if($errors->any())<div class="err">{{ implode(' · ',$errors->all()) }}</div>@endif
<form method="post" action="{{ $zeittarif ? route('zeittarife.update',$zeittarif->intID) : route('zeittarife.store') }}">@csrf @if($zeittarif) @method('PUT') @endif
<div class="grid"><label>Tarif-ID</label><input value="{{ $zeittarif->intID ?? 'neu' }}" disabled><label>Tarifname *</label><input name="strTarifname" maxlength="255" value="{{ old('strTarifname',$zeittarif->strTarifname ?? '') }}" required><label>Freie Sekunden *</label><input type="number" min="0" step="1" name="intFreiSekunden" value="{{ old('intFreiSekunden',$zeittarif->intFreiSekunden ?? 0) }}" required><label>Mindestabnahme Sekunden *</label><input type="number" min="0" step="1" name="intMindestAbnahmeSekunden" value="{{ old('intMindestAbnahmeSekunden',$zeittarif->intMindestAbnahmeSekunden ?? 0) }}" required><label>Takt in Sekunden *</label><input type="number" min="0" step="1" name="intTaktSekunden" value="{{ old('intTaktSekunden',$zeittarif->intTaktSekunden ?? 60) }}" required></div>
<p><button class="button" type="submit">Speichern</button> <a class="button" href="{{ route('zeittarife.index') }}">Schließen</a></p></form>
@if($zeittarif)<div class="zones"><h3>Zeitfenster</h3><div class="hint">Access speichert reine Uhrzeiten als Datum 30.12.1899 plus Uhrzeit. Im Web wird nur die Uhrzeit angezeigt.</div><table><thead><tr><th>ID</th><th>Beginn</th><th>Ende</th><th>Minutenpreis</th><th></th></tr></thead><tbody>
@foreach($zonen as $z)<tr><form method="post" action="{{ route('zeittarife.zonen.update',[$zeittarif->intID,$z->intID]) }}">@csrf @method('PUT')<td>{{ $z->intID }}</td><td><input type="time" step="1" name="datBeginn" value="{{ date('H:i:s',strtotime($z->datBeginn)) }}" required></td><td><input type="time" step="1" name="datEnde" value="{{ date('H:i:s',strtotime($z->datEnde)) }}" required></td><td><input type="number" step="0.000001" min="0" name="fMinutenpreis" value="{{ $z->fMinutenpreis }}" required></td><td><button class="button">Speichern</button></td></form></tr>@endforeach
<tr><form method="post" action="{{ route('zeittarife.zonen.store',$zeittarif->intID) }}">@csrf<td>neu</td><td><input type="time" step="1" name="datBeginn" required></td><td><input type="time" step="1" name="datEnde" required></td><td><input type="number" step="0.000001" min="0" name="fMinutenpreis" required></td><td><button class="button">Hinzufügen</button></td></form></tr></tbody></table></div>@endif
</div><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>
