<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><title>{{ $produkt ? 'Produkt '.$produkt->intID : 'Neues Produkt' }}</title><style>
body{font:13px Arial;background:#d9d9d9;padding:12px;color:#111}.window{max-width:1050px;margin:auto;background:#efefef;border:1px solid #888;padding:14px}.top{display:flex;justify-content:space-between;align-items:center}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 24px}.field{display:grid;grid-template-columns:180px 1fr;gap:8px;align-items:center}.wide{grid-column:1/-1}input,select,textarea{width:100%;padding:5px;border:1px solid #999;background:white}textarea{min-height:130px}.checks{display:flex;gap:28px;padding:6px 0}.checks input{width:auto}.button{padding:7px 13px;border:1px solid #777;background:#eee;color:#111;text-decoration:none;cursor:pointer}.err{background:#fee;border:1px solid #b91c1c;padding:8px;margin-bottom:10px}.ok{background:#e8f6e8;border:1px solid #4b8b4b;padding:8px;margin-bottom:10px}
</style></head><body>
<x-page-help title="Produkte">Hier werden Produktstammdaten und abrechnungsrelevante Zuordnungen gepflegt. Änderungen können spätere Aufträge, DATEV-Zuordnungen und Rechnungen beeinflussen.</x-page-help>
<div class="window"><div class="top"><h2>{{ $produkt ? 'Produkt '.$produkt->intID.' bearbeiten' : 'Neues Produkt' }}</h2><a href="{{ route('frontend.switch','modern') }}">Zum neuen Frontend wechseln →</a></div>
@if(session('status'))<div class="ok">{{ session('status') }}</div>@endif @if($errors->any())<div class="err">{{ implode(' · ',$errors->all()) }}</div>@endif
<form method="post" action="{{ $produkt ? route('produkte.update',$produkt->intID) : route('produkte.store') }}">@csrf @if($produkt) @method('PUT') @endif
@include('produkte._fields')
<p><button class="button" type="submit">Speichern</button> <a class="button" href="{{ route('produkte.index') }}">Zur Produktliste</a></p></form></div><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>
