<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><title>Auftragsposition</title><style>body{font:13px Arial;background:#d9d9d9;padding:12px}.window{max-width:1000px;margin:auto;background:#efefef;border:1px solid #888;padding:14px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px 24px}.field{display:grid;grid-template-columns:170px 1fr;gap:8px;align-items:center}input,select,textarea{width:100%;padding:5px;border:1px solid #999}textarea{min-height:120px}.button{padding:7px 13px;border:1px solid #777;background:#eee;color:#111;text-decoration:none;cursor:pointer}.err{background:#fee;border:1px solid #b91c1c;padding:8px;margin-bottom:10px}</style></head><body>
<x-page-help title="Auftragsverwaltung">Hier suchst, prüfst und bearbeitest du Aufträge und Auftragspositionen. Änderungen an Positionen, Intervallen, Preisen oder Abrechnungsarten wirken auf spätere Rechnungen. Vor dem Speichern deshalb Abrechnungsart und Gültigkeit prüfen.</x-page-help>
<div class="window">
<div style="text-align:right;margin-bottom:10px"><a href="{{ route('frontend.switch', 'modern') }}">Zum neuen Frontend wechseln →</a></div>
<h2>{{ $id ? 'Auftragsposition '.$id.' bearbeiten' : 'Neue Auftragsposition' }} · Auftrag {{ $auftrag->intAufNr }}</h2>
@if($errors->any())<div class="err">{{ implode(' · ',$errors->all()) }}</div>@endif
<form method="post" action="{{ $id ? route('kunden.auftraege.positionen.update',[$kunde->intID,$auftrag->intAufNr,$id]) : route('kunden.auftraege.positionen.store',[$kunde->intID,$auftrag->intAufNr]) }}">@csrf @if($id) @method('PUT') @endif
<div class="grid">
<div class="field" style="grid-column:1/-1"><label>Produkt *</label><select id="product" name="intProduktID" required><option value="">Bitte wählen</option>@foreach($produkte as $p)<option value="{{ $p->intID }}" data-price="{{ $p->fPreis }}" data-description="{{ e($p->strBeschreibung) }}" @selected(old('intProduktID',$position->intProduktID ?? null)==$p->intID)>{{ $p->strKuerzel }} · {{ Str::limit($p->strBeschreibung,90) }}</option>@endforeach</select></div>
<div class="field"><label>Menge</label><input type="number" step="0.01" name="intMenge" value="{{ old('intMenge',$position->intMenge ?? 1) }}" required></div>
<div class="field"><label>Einzelpreis netto</label><input id="price" type="number" step="0.0001" name="fEndpreis" value="{{ old('fEndpreis',$position->fEndpreis ?? 0) }}" required></div>
<div class="field"><label>Fakturieren ab</label><input type="date" name="datFakturierAb" value="{{ old('datFakturierAb',!empty($position->datFakturierAb)?date('Y-m-d',strtotime($position->datFakturierAb)):'') }}"></div>
<div class="field"><label>Fakturieren bis</label><input type="date" name="datFakturierBis" value="{{ old('datFakturierBis',!empty($position->datFakturierBis)?date('Y-m-d',strtotime($position->datFakturierBis)):'') }}"></div>
<div class="field"><label>Rabatt %</label><input type="number" step="0.1" name="fRabattInProzent" value="{{ old('fRabattInProzent',$position->fRabattInProzent ?? 0) }}" required></div>
<div class="field"><label>Mindestlaufzeit Ende</label><div><input id="minlauf" type="date" name="datMindeslaufzeitEnde" value="{{ old('datMindeslaufzeitEnde',!empty($position->datMindeslaufzeitEnde)?date('Y-m-d',strtotime($position->datMindeslaufzeitEnde)):'') }}" required><div style="margin-top:4px"><button class="button" type="button" onclick="setDate('minlauf',0)">Jetzt</button> <button class="button" type="button" onclick="addYear('minlauf')">+1J</button> <button class="button" type="button" onclick="noneDate('minlauf')">keine</button></div></div></div>
<div class="field"><label>Wiedervorlage Vertrieb</label><div><input id="wvdate" type="date" name="datWiedervorlageVertrieb" value="{{ old('datWiedervorlageVertrieb',!empty($position->datWiedervorlageVertrieb)?date('Y-m-d',strtotime($position->datWiedervorlageVertrieb)):'') }}" required><div style="margin-top:4px"><button class="button" type="button" onclick="setWv(-90)">-90T</button> <button class="button" type="button" onclick="setWv(-40)">-40T</button> <button class="button" type="button" onclick="noneDate('wvdate')">keine</button></div></div></div>
<div class="field" style="grid-column:1/-1"><label>Beschreibung</label><textarea id="description" name="strBeschreibung" required>{{ old('strBeschreibung',$position->strBeschreibung ?? '') }}</textarea></div>
<div class="field" style="grid-column:1/-1"><label>WV Notiz</label><textarea name="txtWiedervorlageVertrieb">{{ old('txtWiedervorlageVertrieb',$position->txtWiedervorlageVertrieb ?? '') }}</textarea></div>
</div><p><button class="button" type="submit">Position speichern</button> <a class="button" href="{{ route('kunden.auftraege.show',[$kunde->intID,$auftrag->intAufNr]) }}">Abbrechen</a></p></form></div>
<script>function iso(d){return d.toISOString().slice(0,10)} function setDate(id,days){const d=new Date();d.setDate(d.getDate()+days);document.getElementById(id).value=iso(d)} function addYear(id){const el=document.getElementById(id);const d=el.value?new Date(el.value+'T12:00:00'):new Date();d.setFullYear(d.getFullYear()+1);el.value=iso(d)} function noneDate(id){document.getElementById(id).value='1980-01-01'} function setWv(days){const src=document.getElementById('minlauf').value;const d=src&&src!=='1980-01-01'?new Date(src+'T12:00:00'):new Date();d.setDate(d.getDate()+days);document.getElementById('wvdate').value=iso(d)}document.getElementById('product').addEventListener('change',function(){const o=this.options[this.selectedIndex];if(!o.value)return;if(confirm('Produktinformationen übernehmen? Beschreibung und Preis werden überschrieben.')){document.getElementById('price').value=o.dataset.price||0;document.getElementById('description').value=o.dataset.description||'';}});</script><script src="{{ asset('js/db-window-manager.js') }}"></script></body></html>
