<!DOCTYPE html><html lang="de"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Auftrag {{ $auftrag->intAufNr }}</title>
<style>body{font:13px Arial;background:#d9d9d9;padding:12px}.window{max-width:1180px;margin:auto;background:#efefef;border:1px solid #888;padding:14px}.head{display:flex;gap:70px;font-weight:bold}.section{color:#0000cc;font-weight:bold;border-bottom:2px solid #0000cc;margin:14px 0 10px}.grid{display:grid;grid-template-columns:1fr 1fr;gap:6px 28px}.field{display:grid;grid-template-columns:150px 1fr;gap:8px}.value{background:white;border:1px solid #aaa;padding:4px;min-height:18px}.flags{display:flex;gap:14px;flex-wrap:wrap}.button{display:inline-block;padding:7px 12px;border:1px solid #777;background:#eee;color:#111;text-decoration:none}table{width:100%;border-collapse:collapse;background:#fff;margin-top:8px}th,td{border:1px solid #aaa;padding:5px;vertical-align:top}th{background:#ddd}.money{text-align:right;white-space:nowrap}.muted{color:#666}</style></head><body><div class="window">
<div style="text-align:right;margin-bottom:10px"><a href="{{ route('frontend.switch', 'modern') }}">Zum neuen Frontend wechseln →</a></div>
<div class="head"><div>Auftragsnummer: <span class="value">{{ $auftrag->intAufNr }}</span></div><div>Kundennummer: <span class="value">{{ $kunde->intID }}</span></div></div>
<div class="section">Informationen über den Auftrag</div><div class="grid">
<div class="field"><div>Kunde:</div><div class="value">{{ $kunde->strName }}</div></div><div class="field"><div>Zahlungsbedingung:</div><div class="value">{{ $zahlungsbedingung?->strBezeichnung ?? 'Nicht hinterlegt' }}</div></div>
<div class="field"><div>Rechnungsanschrift:</div><div class="value">{{ $rechnungsanschrift?->strName ?? 'Nicht hinterlegt' }}</div></div><div class="field"><div>Erfassungsdatum:</div><div class="value">{{ $auftrag->datErfassungsdatum ? date('d.m.Y',strtotime($auftrag->datErfassungsdatum)) : '' }}</div></div>
<div class="field"><div>Auftragsbeschreibung:</div><div class="value">{{ $auftrag->strBeschreibung }}</div></div><div class="field"><div>Fakturieren ab:</div><div class="value">{{ $auftrag->datFakturierAb ? date('d.m.Y',strtotime($auftrag->datFakturierAb)) : '' }}</div></div>
<div class="field"><div>Letzte Rechnung:</div><div class="value">{{ $letztesRechnungsdatum ? date('d.m.Y',strtotime($letztesRechnungsdatum)) : '' }}</div></div><div class="field"><div>Storniert ab:</div><div class="value">{{ $auftrag->datStorniereAb ? date('d.m.Y',strtotime($auftrag->datStorniereAb)) : '' }}</div></div>
<div class="field"><div>Angenommen von:</div><div class="value">{{ $auftrag->strAngenommenVon }}</div></div><div class="field"><div>Abrechnungshinweis:</div><div class="value">{{ $auftrag->strAbrechnungshinweis }}</div></div>
</div>
<div class="section">Rechnungsoptionen</div><div class="flags">
<span>☑/☐ Papier: {{ $auftrag->boolPapierrechnung ? 'Ja' : 'Nein' }}</span><span>E-Mail: {{ $auftrag->boolEmailRechnung ? 'Ja' : 'Nein' }}</span><span>Lastschrift: {{ $auftrag->boolLastschriftErzeugen ? 'Ja' : 'Nein' }}</span><span>Dauerlastschrift: {{ $auftrag->boolDauerlastschrift ? 'Ja' : 'Nein' }}</span><span>Rechnungstool: {{ $auftrag->boolRechnungstool ? 'Ja' : 'Nein' }}</span><span>Voraus: {{ $auftrag->boolVoraus ? 'Ja' : 'Nein' }}</span><span>Domain: {{ $auftrag->boolDomainrechnung ? 'Ja' : 'Nein' }}</span><span>Sponsoring: {{ $auftrag->boolSponsoring ? 'Ja' : 'Nein' }}</span><span>Eingefroren: {{ (int)$auftrag->boolEingefroren !== 0 ? 'Ja' : 'Nein' }}</span>
</div>
<div class="section">Skonto</div><table><thead><tr><th>Stufe</th><th>Tage</th><th>Prozent</th></tr></thead><tbody>@for($i=1;$i<=3;$i++)<tr><td>{{ $i }}</td><td>{{ $auftrag->{'intSkonto'.$i.'Tage'} }}</td><td>{{ number_format((float)$auftrag->{'dezSkonto'.$i.'Prozent'},1,',','.') }} %</td></tr>@endfor</tbody></table>
<div class="section">Auftragspositionen</div>@if($positionen->isEmpty())<p>Keine Positionen vorhanden.</p>@else<table><thead><tr><th>ID</th><th>Menge</th><th>Beschreibung</th><th>Einzelpreis netto</th><th>Fakt. ab</th><th>Fakt. bis</th><th>Account?</th><th>Mindestlaufzeit</th><th>Wiedervorlage</th></tr></thead><tbody>
@foreach($positionen as $p)<tr><td><a href="{{ route('kunden.auftraege.positionen.edit',[$kunde->intID,$auftrag->intAufNr,$p->intID]) }}">{{ $p->intID }}</a></td><td>{{ rtrim(rtrim(number_format((float)$p->intMenge,2,',','.'),'0'),',') }}</td><td>{!! nl2br(e($p->strBeschreibung)) !!}</td><td class="money">{{ number_format((float)$p->fEndpreis,4,',','.') }} €</td><td>{{ $p->datFakturierAb ? date('d.m.Y',strtotime($p->datFakturierAb)) : '' }}</td><td>{{ $p->datFakturierBis ? date('d.m.Y',strtotime($p->datFakturierBis)) : '' }}</td><td>{{ $p->boolIstAnbindung ? 'Ja' : 'Nein' }}</td><td>{{ $p->datMindeslaufzeitEnde ? date('d.m.Y',strtotime($p->datMindeslaufzeitEnde)) : '' }}</td><td>{{ $p->datWiedervorlageVertrieb ? date('d.m.Y',strtotime($p->datWiedervorlageVertrieb)) : '' }}</td></tr>@endforeach</tbody></table>@endif
<p><a class="button" href="{{ route('kunden.auftraege.index',$kunde->intID) }}">Zur Auftragsliste</a> <a class="button" href="{{ route('kunden.show',$kunde->intID) }}">Zurück zum Kunden</a></p></div></body></html>
